### ISSUE TITLE
[GOG] Can't install games

### ISSUE THREAD

**Issue by Nocifer** [Heroic-Games-Launcher/HeroicGamesLauncher#1018]
### Describe the bug

When I select a game from my GOG library to go to its info page, I get the following error:

```
(15:12:11) ERROR:   [Backend]:         Error: Command failed: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 2 --token="..." --lang=en-US --os windows
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Fallout 2 Classic with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 1
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
Traceback (most recent call last):
  File "gogdl/cli.py", line 35, in <module>
  File "gogdl/cli.py", line 32, in main
  File "gogdl/dl/manager.py", line 39, in calculate_download_size
  File "gogdl/dl/manager.py", line 146, in get_download_metadata
  File "gogdl/dl/manager.py", line 349, in handle_dependencies
KeyError: 'targetDir'
[17537] Failed to execute script 'cli' due to unhandled exception!
```

Afterwards, clicking "Install" displays the loading/refresh animation but nothing further happens; meanwhile, after ~10-20 seconds I get one more instance of the exact same error in the log.

### Add logs

(15:09:00) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(15:09:00) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:09:00) INFO:    [Backend]:         
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.16.11-arch1-1 ARCH: x64
  CPU: AMD Ryzen 5 3600 6-Core Processor @3.6 GOVERNOR: schedutil
  RAM: Total: 16.7 GB Available: 9.76 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1660 SUPER VRAM: 6144MB DRIVER: 510.54 
  PROTOCOL: x11
  
(15:09:00) INFO:    [Gog]:             Getting data about the user
(15:09:00) WARNING: [Backend]:         Protocol already registered.
(15:09:01) INFO:    [Gog]:             Saved user data to config
(15:09:01) INFO:    [Frontend]:        Refreshing Library
(15:09:01) INFO:    [Gog]:             Getting GOG library
(15:09:02) INFO:    [Gog]:             Number of library pages: 4
(15:09:02) INFO:    [Gog]:             Getting data for page 2
(15:09:02) INFO:    [Gog]:             Getting data for page 3
(15:09:03) INFO:    [Gog]:             Getting data for page 4
(15:09:03) INFO:    [Gog]:             Saved games data
(15:09:03) INFO:    [Legendary]:       Refreshing library...
(15:09:03) INFO:    [Legendary]:       Refreshing Epic Games...
(15:09:03) INFO:    [Legendary]:       Refreshing Epic Games...
(15:09:04) INFO:    [Legendary]:       [cli] INFO: Logging in...
(15:09:04) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(15:09:06) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(15:09:06) INFO:    [Backend]:         checking for heroic updates
(15:09:06) INFO:    [Backend]:         skipping heroic updates
(15:09:06) INFO:    [Legendary]:       Updating game list
(15:09:06) INFO:    [Legendary]:       Game List Updated
(15:09:08) INFO:    [Legendary]:       Checking for game updates
(15:09:08) INFO:    [Legendary]:       Found 0 game(s) to update
(15:09:08) INFO:    [Gog]:             Found 0 game(s) to update
(15:12:11) ERROR:   [Backend]:         Error: Command failed: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 2 --token="..." --lang=en-US --os windows
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Fallout 2 Classic with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 1
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
Traceback (most recent call last):
  File "gogdl/cli.py", line 35, in <module>
  File "gogdl/cli.py", line 32, in main
  File "gogdl/dl/manager.py", line 39, in calculate_download_size
  File "gogdl/dl/manager.py", line 146, in get_download_metadata
  File "gogdl/dl/manager.py", line 349, in handle_dependencies
KeyError: 'targetDir'
[17537] Failed to execute script 'cli' due to unhandled exception!

(15:12:48) ERROR:   [Backend]:         Error: Command failed: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 2 --token="..." --lang=en-US --os windows
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Fallout 2 Classic with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 1
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
Traceback (most recent call last):
  File "gogdl/cli.py", line 35, in <module>
  File "gogdl/cli.py", line 32, in main
  File "gogdl/dl/manager.py", line 39, in calculate_download_size
  File "gogdl/dl/manager.py", line 146, in get_download_metadata
  File "gogdl/dl/manager.py", line 349, in handle_dependencies
KeyError: 'targetDir'
[17554] Failed to execute script 'cli' due to unhandled exception!

### Steps to reproduce

1. Go to your GOG library
2. Click on a game to visit its info page
3. See error in the log
4. Click "Install"
5. See the same error in the log

### Expected behavior

Game should install.

### System Information

- OS: Arch Linux
- Heroic Version: 2.2.1

**Comment by SaschaVasarrhelyi** [comment]
Hi i have a similar Problem with a Hand full of GOG Games. Heroic can not detect the Download- size and the Installed size and without this information Heroic get an Error but i don' t know why.

Here is an List of the Games that affect from this, hope it helps. I don't know???

Leisure Suit Larry: Magna Cum Laude: Uncut and Uncensored!
Corsairs Gold
Giana Sisters: Rise of the Owlverlord
Indiana Jones® and the Emperor's Tomb™
King's Quest 8 - Mask of Eternity
Monkey Island™ 2 Special Edition: LeChuck’s Revenge™
Rise of the Triad (2013)
Sid Meier’s Pirates!
Europa Universalis II

My log says about an "Error: Command failes:... " to but i don't know how to delete this Token.

"p.S. : The rest of the Games that i have on GOG are not affected by this Bug.
And i started the gogdl in the opt Heroic directory with the Tokenstring from the log and get following Errormassages:

/opt/Heroic/resources/app.asar.unpacked/build/bin/linux$ ./gogdl --token="3Qa3Mi2eG51r8cqiZ7F7JWpHcn1QzfS5rNxdBKBrarGZiBf4jtMJTbHWNK5hlfGK_cRa0y7LjH-g62ur-t9le6JnqQnqICku1ndHcayw24hswtaY262EOYPEnmpgKXu_7mxk-g5evSRx1SqCOM6HUt56kskta1NMSYZI4xpTRnc6m68pJsF-kTTd7HIXIJPW" --lang=en-US --os windows repair info
Traceback (most recent call last):
  File "requests/compat.py", line 12, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "charset_normalizer/utils.py", line 2, in <module>
ModuleNotFoundError: No module named 'unicodedata2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gogdl/cli.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "gogdl/dl/manager.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "requests/__init__.py", line 45, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "requests/exceptions.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "requests/compat.py", line 14, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer/__init__.py", line 24, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer/api.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer/cd.py", line 9, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer/md.py", line 5, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer/utils.py", line 4, in <module>
ModuleNotFoundError: No module named 'unicodedata'
[11542] Failed to execute script 'cli' due to unhandled exception!

Greetings 
Sascha

**Comment by SaschaVasarrhelyi** [comment]
Hi, i test the Command You wrote in You're last Post with the no change but the following result in the Terminal:

 /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 2 --token="removed" --lang=en-US --os windows
Traceback (most recent call last):
  File "gogdl/cli.py", line 35, in <module>
  File "gogdl/cli.py", line 32, in main
  File "gogdl/dl/manager.py", line 39, in calculate_download_size
  File "gogdl/dl/manager.py", line 88, in get_download_metadata
TypeError: 'NoneType' object does not support item assignment
[25772] Failed to execute script 'cli' due to unhandled exception!

Good Night
Sascha

**Comment by arrowgent** [comment]
ubuntu 18.04
modified gogdl

can confirm it does not get the download size on info page
but im having no issue downloading games and running them
download size is given on the install location prompt window
![pir_ate_s](https://user-images.githubusercontent.com/57545549/155921073-9351c1fc-172c-4b7e-8501-7212b1c6ba57.png)



pirates!
```
(19:44:19) INFO:    [Gog]:             Installing 1207661643 with: /home/catbox/.local/bin/heroic_dist/resources/app.asar.unpacked/build/bin/linux/gogdl download 1207661643 --platform linux --path="/media/catbox/CrucialXTB/legendary_egs/games" --skip-dlcs --lang="en"  |& tee "/home/catbox/.config/heroic/GamesConfig/1207661643.log"
(19:44:21) INFO:    [Backend]:         Progress: 1207661643 /MiB/undefined
(19:44:22) INFO:    [Backend]:         Progress: 1207661643 /MiB/undefined
(19:44:24) INFO:    [Backend]:         Progress: 1207661643 /MiB/undefined
(19:44:25) INFO:    [Backend]:         finished installing
(19:44:26) INFO:    [Frontend]:        Refreshing Library
(19:44:26) INFO:    [Gog]:             Getting GOG library
(19:44:26) INFO:    [Gog]:             Number of library pages: 2
(19:44:26) INFO:    [Gog]:             Getting data for page 2
(19:44:27) INFO:    [Gog]:             Saved games data
(19:44:27) INFO:    [Legendary]:       Refreshing library...
(19:44:27) INFO:    [Legendary]:       Updating game list
(19:44:27) INFO:    [Legendary]:       Game List Updated
(19:45:15) INFO:    [Gog]:             Removing /media/catbox/CrucialXTB/legendary_egs/games/Pirates
(19:45:15) INFO:    [Backend]:         finished uninstalling
(19:45:16) INFO:    [Frontend]:        Refreshing Library
```


ROTT
```
(19:45:16) INFO:    [Gog]:             Getting GOG library
(19:45:16) INFO:    [Backend]:         Desktop shortcut removed
(19:45:16) INFO:    [Backend]:         Applications shortcut removed
(19:45:16) INFO:    [Gog]:             Number of library pages: 2
(19:45:16) INFO:    [Gog]:             Getting data for page 2
(19:45:17) INFO:    [Gog]:             Saved games data
(19:45:17) INFO:    [Legendary]:       Refreshing library...
(19:45:17) INFO:    [Legendary]:       Updating game list
(19:45:17) INFO:    [Legendary]:       Game List Updated
(19:45:49) INFO:    [Gog]:             Installing 1207658732 with: /home/catbox/.local/bin/heroic_dist/resources/app.asar.unpacked/build/bin/linux/gogdl download 1207658732 --platform linux --path="/media/catbox/CrucialXTB/legendary_egs/games" --skip-dlcs --lang="en"  |& tee "/home/catbox/.config/heroic/GamesConfig/1207658732.log"
(19:45:51) INFO:    [Backend]:         Progress: 1207658732 /MiB/undefined
(19:45:52) INFO:    [Backend]:         Progress: 1207658732 0.00/0.00
MiB/641:36:00
(19:45:54) INFO:    [Backend]:         Progress: 1207658732 /MiB/undefined
(19:45:54) INFO:    [Backend]:         finished installing
(19:45:55) INFO:    [Frontend]:        Refreshing Library
(19:48:54) INFO:    [Gog]:             Removing /media/catbox/CrucialXTB/legendary_egs/games/Rise of the Triad
(19:48:54) INFO:    [Backend]:         finished uninstalling
(19:48:54) INFO:    [Frontend]:        Refreshing Library
```

**Comment by Nocifer** [comment]
@arrowgent You were right, it's only this particular game that has the issue, all the others (that I've tested) are downloading and installing correctly, and also showing their info (download & install size).

The game in question is Fallout 2 Classic, which was the original version of Fallout 2 in GOG's catalog before it was removed a few years ago and later re-added under a new store entry due to a change in publishing rights. Maybe that's why Heroic can't find it, because it's not in the store?

**Comment by arrowgent** [comment]
> @arrowgent You were right, it's only this particular game that has the issue, all the others (that I've tested) are downloading and installing correctly, and also showing their info (download & install size).
> 
> The game in question is Fallout 2 Classic, which was the original version of Fallout 2 in GOG's catalog before it was removed a few years ago and later re-added under a new store entry due to a change in publishing rights. Maybe that's why Heroic can't find it, because it's not in the store?

quite interesting -- yes i know about some games removed that the owners still have access to.

can i ask if minigalaxy has this issue?
https://github.com/sharkwouter/minigalaxy/

this would determine if its a problem with gog's api, or heroic launcher's gog api

**Comment by imLinguin** [comment]
Please test this build: https://github.com/imLinguin/HeroicGamesLauncher/actions/runs/1918008682
It contains gogdl testing branch, see if it solves issues for you.

**Comment by SaschaVasarrhelyi** [comment]
Hi,

Corsairs Gold give me the Installsize and download allright.

Gina Sisters: Rise of the Owlverlord give me the Installsize and download allright. But ETA junps from 07:48:18 to 777867544:45:34 and back but downloadrate on my Systemmonitor are constantly by 6,5 - 7,0 MB/s but it's no problem then the downloads and that's the main thing. And it installs allright.

Indiana Jones and the Emeror's Tomb give me the installsize and download successful and install nice.

Leisure Suit Larry: Magna Cum Laude: Uncut an Uncensored! gives me the Installsize and download allright. Calculating of ETA are verry inaccurate (downloadtime from 9 billion h :) ) but install successful and shows normal and thanks God it don't take 9 billion h to download ;)

Rise of the Triad (2013) give me the information it needs to install and download and install successful.

Sid Meier's Pirates! (Live the Life) brings Downloadsize and installs successful.


All are good, thank You very much.

**Comment by Nocifer** [comment]
> Please test this build: https://github.com/imLinguin/HeroicGamesLauncher/actions/runs/1918008682
> It contains gogdl testing branch, see if it solves issues for you.

Yup, it now works properly.

**Comment by Rhystic1** [comment]
I have the same problem on my Steam Deck and it is applying to every game in my GOG library. Since I cannot build the fork that was linked, could someone upload the AppImage version of that build somewhere where I can dowload it?

**Comment by imLinguin** [comment]
https://github.com/imLinguin/HeroicGamesLauncher/actions/runs/1938511251
here is new build, that fixes more things. You don't have to build anything, that's why it's a link to the action with built binaries.
Just scroll a bit down (Artifacts section)

**Comment by Rhystic1** [comment]
> https://github.com/imLinguin/HeroicGamesLauncher/actions/runs/1938511251 here is new build, that fixes more things. You don't have to build anything, that's why it's a link to the action with built binaries. Just scroll a bit down (Artifacts section)

Weird, it wouldn't let me download from there previously...
Oh well, now it is! Thank you!

**Comment by flavioislima** [comment]
> I have the same problem on my Steam Deck and it is applying to every game in my GOG library. Since I cannot build the fork that was linked, could someone upload the AppImage version of that build somewhere where I can dowload it?

Yes. On steam deck only epic games are working for now. We are investigating the issue.

**Comment by Unruly01** [comment]
Been haveing a Issue were it's not letting me start a download at all.

**Comment by wiryfuture** [comment]
Fixed?
