### ISSUE TITLE
Built-in Legendary binary not found

### ISSUE THREAD

**Issue by Abacta** [Heroic-Games-Launcher/HeroicGamesLauncher#1077]
### Describe the bug

After updating to 2.2.5, the "legendary version" in the settings menu was displaying that the version was invalid, resulting in being unable to log out from the epic account.

### Add logs

(17:43:28) INFO:    [Legendary]:       Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:43:28) INFO:    [Gog]:             Location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:43:29) ERROR:   [Legendary]:       Error: Command failed: legendary --version
/bin/sh: 1: legendary: not found

(17:43:29) INFO:    [Backend]:         
  Heroic Version: 2.2.5 Oden
  Legendary Version: invalid
  OS: Ubuntu KERNEL: 5.13.0-35-generic ARCH: x64
  CPU: Intel Core™ i3-8130U @2.2 GOVERNOR: powersave
  RAM: Total: 3.86 GB Available: 1.1 GB
  GRAPHICS: GPU0: UHD Graphics 620  VRAM: 256MB DRIVER:  
  PROTOCOL: x11
  
(17:43:30) WARNING: [Backend]:         Protocol already registered.
(17:43:32) INFO:    [Frontend]:        Refreshing Library
(17:43:32) INFO:    [Legendary]:       Refreshing library...
(17:43:32) INFO:    [Legendary]:       Refreshing Epic Games...
(17:43:32) INFO:    [Legendary]:       Refreshing Epic Games...
(17:43:33) ERROR:   [Legendary]:       Error: spawn legendary ENOENT
(17:43:34) INFO:    [Legendary]:       Updating game list
(17:43:34) INFO:    [Legendary]:       Game List Updated
(17:43:35) ERROR:   [Legendary]:       Error: Command failed: legendary list-installed --check-updates --tsv
/bin/sh: 1: legendary: not found

(17:43:35) INFO:    [Gog]:             Found 0 game(s) to update
(17:43:35) ERROR:   [Frontend]:        Error: Error invoking remote method 'checkGameUpdates': TypeError: legendaryUpdates is not iterable
(17:43:37) INFO:    [Backend]:         checking for heroic updates
(17:43:37) ERROR:   [Backend]:         Could not check for new version of heroic
(17:43:38) ERROR:   [Legendary]:       Error: Command failed: legendary --version
/bin/sh: 1: legendary: not found

### Steps to reproduce

1. Go to "Manage Accounts";
2. Click to log out from Epic;
3. Program restarts and does not log out the account.

### Expected behavior

It should prevent the action or warn that the Legendary binary is missing.

### System Information

- OS Ubuntu 20.04 LTS
- Heroic Version 2.2.5 (Hotfix 4)

**Comment by KrishWu** [comment]
+1 Macos

(18:28:30) INFO:    [Legendary]:       Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(18:28:30) INFO:    [Gog]:             Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(18:28:32) ERROR:   [Legendary]:       Error: Command failed: legendary --version
/bin/sh: legendary: command not found

(18:28:36) INFO:    [Backend]:         
  Heroic Version: 2.2.5 Oden
  Legendary Version: invalid
  OS: macOS KERNEL: 21.3.0 ARCH: x64
  CPU: Intel Core™ i7-6920HQ @2.9 
  RAM: Total: 17.2 GB Available: 10.9 GB
  GRAPHICS: GPU0: Intel HD Graphics 530 VRAM: 1536MB DRIVER:  GPU1: AMD Radeon Pro 460 VRAM: 4096MB DRIVER:  
  
  
(18:28:37) WARNING: [Backend]:         Protocol already registered.
(18:28:38) INFO:    [Frontend]:        Refreshing Library
(18:28:38) INFO:    [Legendary]:       Refreshing library...
(18:28:38) INFO:    [Legendary]:       Refreshing Epic Games...
(18:28:38) INFO:    [Legendary]:       Refreshing Epic Games...
(18:28:39) ERROR:   [Legendary]:       Error: spawn legendary ENOENT
(18:28:39) INFO:    [Legendary]:       Updating game list
(18:28:39) INFO:    [Legendary]:       Game List Updated
(18:28:40) ERROR:   [Legendary]:       Error: Command failed: legendary list-installed --check-updates --tsv
/bin/sh: legendary: command not found

(18:28:40) INFO:    [Gog]:             Found 0 game(s) to update
(18:28:40) ERROR:   [Frontend]:        Error: Error invoking remote method 'checkGameUpdates': TypeError: legendaryUpdates is not iterable
(18:28:41) INFO:    [Backend]:         launching Rocket League® Sugar
(18:28:42) INFO:    [Legendary]:       Launch Command: 
(18:28:43) INFO:    [Backend]:         checking for heroic updates
(18:28:50) ERROR:   [Backend]:         Error - Command failed: ./legendary launch Sugar    
[cli] INFO: Logging in...
[Core] INFO: Logging in...
[cli] INFO: Checking for updates...
[cli] CRITICAL: Metadata for "Sugar" does not exist, cannot launch!

(18:28:53) ERROR:   [Legendary]:       Error: Command failed: legendary --version
/bin/sh: legendary: command not found

**Comment by flavioislima** [comment]
can you try now on 2.2.6?

**Comment by Abacta** [comment]
it's working properly now, thanks

**Comment by UnchoppedPork** [comment]
I believe I have the same issue on 2.2.6 

(21:41:21) INFO:    [Legendary]:       Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(21:41:21) INFO:    [Gog]:             Location: /Applications/Heroic.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(21:41:30) INFO:    [Backend]:         
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: macOS KERNEL: 21.4.0 ARCH: x64
  CPU: Intel Core™ i7-8559U @2.7 
  RAM: Total: 17.2 GB Available: 10.6 GB
  GRAPHICS: GPU0: Intel Iris Plus Graphics 655 VRAM: 1536MB DRIVER:  
  
  
(21:41:30) WARNING: [Backend]:         Protocol already registered.
(21:41:31) INFO:    [Frontend]:        Refreshing Library
(21:41:31) INFO:    [Legendary]:       Refreshing library...
(21:41:31) INFO:    [Legendary]:       Refreshing Epic Games...
(21:41:31) INFO:    [Legendary]:       Refreshing Epic Games...
(21:41:35) INFO:    [Legendary]:       [cli] INFO: Logging in...
(21:41:35) INFO:    [Legendary]:       [Core] INFO: Trying to re-use existing login session...
(21:41:35) INFO:    [Legendary]:       [cli] INFO: Getting game list... (this may take a while)
(21:41:35) INFO:    [Backend]:         checking for heroic updates
(21:41:37) INFO:    [Legendary]:       Updating game list
(21:41:37) INFO:    [Legendary]:       Game List Updated
(21:41:43) ERROR:   [Legendary]:       Error: Command failed: legendary list-installed --check-updates --tsv
[cli] INFO: Logging in to check for updates...
[Core] INFO: Trying to re-use existing login session...
Traceback (most recent call last):
  File "legendary/cli.py", line 3004, in <module>
  File "legendary/cli.py", line 2917, in main
  File "legendary/cli.py", line 293, in list_installed
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 19: ordinal not in range(128)
[48397] Failed to execute script 'cli' due to unhandled exception!

(21:41:43) INFO:    [Gog]:             Found 0 game(s) to update
(21:41:43) ERROR:   [Frontend]:        Error: Error invoking remote method 'checkGameUpdates': TypeError: legendaryUpdates is not iterable

**Comment by ahmed12magdy** [comment]
I have the same problem
(20:48:43) INFO:    [Legendary]:       Launch Command: 

(20:48:52) ERROR:   [Backend]:         Error - Command failed: ./legendary launch 9d2d0eb64d5c44529cece33fe2a46482    

[cli] INFO: Logging in...

[Core] INFO: Trying to re-use existing login session...

[cli] INFO: Checking for updates...

[cli] CRITICAL: Metadata for "9d2d0eb64d5c44529cece33fe2a46482" does not exist, cannot launch!
