### ISSUE TITLE
Social features

### ISSUE THREAD

**Issue by billcipher225** [Heroic-Games-Launcher/HeroicGamesLauncher#1093]
### Problem description

I can never see which of my friends are online or offline unless I open a game with social features.

### Feature description

A tab to view my current friends list, add new friends, remove friends and block people.

### Additional information

This might be a duplicate request, but I have not found another issue like this.

**Comment by flavioislima** [comment]
Unfortunately, there is no way of doing that for now for Linux or Mac. On Windows you can install the epic overlay with legendary and should work.
Just follow the instructions on the website.
If it starts working on Linux at least, we could add an option for that.

If you are actually talking about list of friends inside heroic, there is no way of doing that since the Epic API is closed source.

**Comment by Dnblgn07** [comment]
> Unfortunately, there is no way of doing that for now for Linux or Mac. On Windows you can install the epic overlay with legendary and should work. Just follow the instructions on the website. If it starts working on Linux at least, we could add an option for that.
> 
> If you are actually talking about list of friends inside heroic, there is no way of doing that since the Epic API is closed source.

I have heroic and epic games both on my mac can I use normal epic games just for joining my friends
