### ISSUE TITLE
Arm

### ISSUE THREAD

**Issue by rbcoder117** [Heroic-Games-Launcher/HeroicGamesLauncher#1131]
### Problem description

You should add it for armf and arm64. You can contact some people on Botspot/Pi-Apps

### Feature description

So you can play on more low end devices

**Comment by JakobDev** [comment]
This Launcher is for Heroic/GOG. None of those 2 platforms provide ARM Binaries of their Games.

**Comment by flavioislima** [comment]
Yes. I belive you can run Heroic on Arm using an emulator. There are a few articles and videos online on how to do that, not specific to heroic though.

**Comment by CactiChameleon9** [comment]
Hey, I know this issue has been closed but I would like an arm64 linux build anyway. MacOS and recently Windows now have arm64 builds - so I think a linux build is not out of the question.

I understand it may not be the most useful - but with some tinkering someone could potentially get something like box64 working with heroic.

**Comment by imLinguin** [comment]
True, if somebody adds the support it will be merged for sure.  
As far as I am aware none of the most active contributors have ARM Linux device

**Comment by ell1e** [comment]
I would also love to use this on my Raspberry Pi 5, if it ever came to be.

**Comment by ell1e** [comment]
> You can run Heroic itself in Box64
https://boilingsteam.com/new-version-of-box86-and-box64-unlocks-steam-big-picture-mode-and-heroic-games-launcher-on-arm/

For what it's worth, this isn't the case on musl libc systems since Box64 doesn't run on that, and even if it did, Heroic might not run directly on that either. Having a flatpak glibc ARM64 release of heroic that integrates box64 or FEX would solve that problem, I assume.

**Comment by sand-undertale** [comment]
tryna use it on my switch and this is so needed
