### ISSUE TITLE
Heroic deleted my entire ~/.wine directory when I uninstalled a game

### ISSUE THREAD

**Issue by DanBaur** [Heroic-Games-Launcher/HeroicGamesLauncher#1209]
### Describe the bug

When I uninstalled the game I also clicked the check-box offering to also remove the associated wine prefix. I assumed it would only delete the data for this game which was stored in the default ~/.wine directory instead of the whole directory. 

### Add logs

Unfortunately I forgot to do this step before uninstalling heroic

### Steps to reproduce

1. Uninstall a game
2. Check the box that offers to delete the wine prefix for the game
3. Click the uninstall button

### Expected behavior

Clicking the check-box should have only deleted the data for the specific game I was removing not the entire root default wine prefix folder.

### System Information

- OS Fedora 35
- Heroic Version 2.2.6 rpm package downloaded from this repo's releases page
- I use proton GE as the default compatibility layer in Heroic

### Additional information

I already deleted the game's respective folder in the appdata folder in ~/.wine a long time ago and forgot about that when I checked the box during the uninstall process.

**Comment by redromnon** [comment]
Heroic clearly asks to **delete the selected wine prefix folder** in the dialog box when uninstalling. So it's basically doing its job here.

That's why Heroic auto-assigns a separate wine prefix folder whenever a game is installed. Moreover, users are advised to use separate prefixes for each game and not the root `~/.wine` folder.

Maybe a check can be implemented for users who've assigned `~/.wine` as the prefix folder for a game or something.

**Comment by flavioislima** [comment]
As you said, heroic explicitly says that will delete the prefix if you check the box, that is unchecked by default. Another check is not necessary.
