### ISSUE TITLE
Support offline GOG installers (making login optional) 

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Heroic-Games-Launcher/HeroicGamesLauncher#1242]
### Problem description

Currently Heroic doesn't support the offline GOG installers, it HAS to connect to the GOG account, no matter what, to download the games itself, it can't just use an already downloaded installer.

### Feature description

Heroic should be able to install the offline installers, and be able to work without logging in to GOG.

### Alternatives

N/A

### Additional information

N/A

**Comment by flavioislima** [comment]
You can install the game and then import it using Heroic instead of downloading it again.
so just install using wine and then select the folder with the game when importing.

**Comment by TheFrenchGhosty** [comment]
@flavioislima That really isn't the same thing though, since it requires installing it outside of Heroic completely (instead of Heroic handling the whole process).

**Comment by flavioislima** [comment]
Yes but heroic don't have knowledge if the installer worked or not. So it's hard to keep track unless we have a way of manually adding the information like lutris does.
Once we have that we can think about offline installer but for now it will be complicated to maintain both types of instalations.

**Comment by TheFrenchGhosty** [comment]
>Once we have that we can think about offline installer but for now it will be complicated to maintain both types of instalations.

So... isn't it a good idea to keep this issue open until this is a thing?

**Comment by imLinguin** [comment]
I believe what you are looking for will be `Heroic` runner which will allow you to add software manually

**Comment by ell1e** [comment]
For what it's worth, minigalaxy supports this without requiring the user to download and run the installer manually. This is useful because minigalaxy will also archive the installers if desired, so that they can be easily transferred to another machine and/or archived for backups. The `Heroic` runner I assume won't do any of that for you.

**Comment by Isaac-Clarke** [comment]
### HELLO WORLD.

For a lapse of time unknown to me, **now Offline GOG Installers can be used** to install GOG games directly into Heroic!

.

Leaving my personal ignorance about "how Heroic works" aside, I ran into an issue:

I managed to install _Blood Fresh Supply_ pretty easily, but _GRAVEN_ instead not, because the launcher is asking "for Part 2 of the installer", which is a .bin file.
I KNOW the Offline Installer works because I've used it on Windows. _For some reason it can't be seen there_.

---

I am all for a platform which "makes installing and playing games as easy as with Steam", because games are meant to be enjoyed, not troubleshot.

![Image](https://github.com/user-attachments/assets/6f07c92d-1951-4edf-b51c-1a727e1a0397)

I do not care for tribalism or whatever.
I am not a knight for any group, software, hardware or corporation.

### I just want to know if I am doing something wrong here, or if this is a shortcoming of the software, because Linux is notorious to not only being harder than Windows, but _also for not having clear instructions to be found anywhere_.
