### ISSUE TITLE
Add multiple accounts 

### ISSUE THREAD

**Issue by iMonZ** [Heroic-Games-Launcher/HeroicGamesLauncher#1260]
### Problem description

I can’t multiple gog accounts
For example my friend and I have both gog accounts.

### Feature description

To add multiple gog accounts.

### Alternatives

There is no alternative

**Comment by flavioislima** [comment]
You are the 1000 person to ask that, maybe we should put on the issue description that this is not going to happen.

**Comment by iMonZ** [comment]
Is there a specific reason for that? @flavioislima

**Comment by flavioislima** [comment]
Besides ethical reasons?
As you said: `my friend and I have both gog accounts.` 
But if you read the contract you signed on GOG or on EPIC, and I know no one does, you will see that the account should not be shared.

So this could put Heroic in a complex situation in ethical terms.

Besides that, is a feature that is pretty boring to maintain since we need to deal with different configs, folders, files, etc.

If you really want that, you could just create a script to change the accounts by renaming the folders where Heroic stores the configurations.

**Comment by iMonZ** [comment]
> Besides ethical reasons? As you said: `my friend and I have both gog accounts.` But if you read the contract you signed on GOG or on EPIC, and I know no one does, you will see that the account should not be shared.
> 
> So this could put Heroic in a complex situation in ethical terms.
> 
> Besides that, is a feature that is pretty boring to maintain since we need to deal with different configs, folders, files, etc.
> 
> If you really want that, you could just create a script to change the accounts by renaming the folders where Heroic stores the configurations.

This is right incase. 
Since he is using my Console too and there is no user switching this is the only way.

**Comment by flavioislima** [comment]
If you mean steam deck as a console then you need to ask Valve to support multiple accounts on the deck, not us. With a different account on the deck heroic would user a different config folder.

**Comment by Kreyren** [comment]
> If you mean steam deck as a console then you need to ask Valve to support multiple accounts on the deck, not us. With a different account on the deck heroic would user a different config folder. -- @flavioislima (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1260#issuecomment-1114214367)

Why do you even bother replying to issues when you just piss everyone off with the attitude of a spoiled child? The feature request is legitimate and addresses a major quality of life hindrance for handheld users.

**Comment by flavioislima** [comment]
> > If you mean steam deck as a console then you need to ask Valve to support multiple accounts on the deck, not us. With a different account on the deck heroic would user a different config folder. -- @flavioislima (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1260#issuecomment-1114214367)
> 
> Why do you even bother replying to issues when you just piss everyone off with the attitude of a spoiled child? The feature request is legitimate and addresses a major quality of life hindrance for handheld users.
> 

Yes, you are right. Sorry. 
I started this project just because I'm a spoiled child.

I should simply accept all feature requests that everyone asks, right? Be a good boy. 

I mean, what is the point of spending thousands of hours of my life that I could use for other stuff like my hobbies, friends and family building a project if I'm not willing to accept what everyone asks me to do?

I should dedicate my whole life and day to the project, 24h, because only spoiled children needs to sleep.

Sorry for not Implementing a feature you want to much and could probably lead to a lot of support requests that would be something that I should do with pleasure during my 24h dedicated to the project.

Thanks for your comment, I'm pretty sure now I'm 100x more motivated to work on this feature. 
You made my day 😊

**Comment by Azarilh** [comment]
> > > If you mean steam deck as a console then you need to ask Valve to support multiple accounts on the deck, not us. With a different account on the deck heroic would user a different config folder. -- @flavioislima ([#1260 (comment)](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1260#issuecomment-1114214367))
> > 
> > 
> > Why do you even bother replying to issues when you just piss everyone off with the attitude of a spoiled child? The feature request is legitimate and addresses a major quality of life hindrance for handheld users.
> 
> Yes, you are right. Sorry. I started this project just because I'm a spoiled child.
> 
> I should simply accept all feature requests that everyone asks, right? Be a good boy.
> 
> I mean, what is the point of spending thousands of hours of my life that I could use for other stuff like my hobbies, friends and family building a project if I'm not willing to accept what everyone asks me to do?
> 
> I should dedicate my whole life and day to the project, 24h, because only spoiled children needs to sleep.
> 
> Sorry for not Implementing a feature you want to much and could probably lead to a lot of support requests that would be something that I should do with pleasure during my 24h dedicated to the project.
> 
> Thanks for your comment, I'm pretty sure now I'm 100x more motivated to work on this feature. You made my day 😊

People tend to pretend more from developers that work for FREE instead of being thankful for their work. The spoiled is the one that doesn't appreciate this free work. I also would like the ability to change account but all i would do is to show interest and not be entitled by requesting it as if i am your boss. lmao
I bet those people didn't even donate.

Have a good day and thank you for your app.
