### ISSUE TITLE
Add an option to replace the Recently played with Installed games

### ISSUE THREAD

**Issue by ShimonHoranek** [Heroic-Games-Launcher/HeroicGamesLauncher#1264]
### Feature description

An option to replace the Recently played section with Installed games. The Recently played section shows even games that I don't have Installed. A section showing Installed games on the other side would show only games., that are ready to play. Additionally, there could be an option to sort the installed games by the time they were last played.

**Comment by arielj** [comment]
This should be fixed in the next release:

- you will be able to sort the list of games by installed games first
- you will be able to disable the `recently played` section

About sorting the installed games by the time they were played, we don't have that in the works, it's only alphabetical (the recently played section should keep track of the last played order)

I want to add an option to remove elements from recently played (to get rid of uninstalled games for example if needed)
