### ISSUE TITLE
Wine prefix contains symlinks to local documents

### ISSUE THREAD

**Issue by djibux** [Heroic-Games-Launcher/HeroicGamesLauncher#1390]
Hello,

I just found out that "My Documents" (and other folders such as "My Pictures", "My Videos"…) in a wine prefix are symlinks to Linux folders.

I would like an option to opt-out of that feature and have each game have its own environment.  The games I install create lots of folders in my Linux documents and I just don't want to see them there.

Lutris provides such an option "Create a sandbox for Wine folders".

Thanks.

**Comment by flavioislima** [comment]
Just use Winetricks to setup the prefix as sandboxed. Heroic will use wine defaults and this is how it is.

**Comment by Keelhauled** [comment]
Something should probably be done about this anyway. I blocked heroic from accessing my documents folder with flatseal and because of these symlinks my witcher saves are gone now (luckily I was not very far since it was just one session). I realize it's my own fault but it would have been preventable if heroic had `--persist=.` or these symlinks didn't exist.
