### ISSUE TITLE
Import entire folder of games

### ISSUE THREAD

**Issue by butterbutts** [Heroic-Games-Launcher/HeroicGamesLauncher#1709]
### Problem description

Right now you can only import one game at a time. This is a slow process if you have many games installed.

### Feature description

Add a "Scan folder for games" option that allows the user to choose a folder where all of their Epic or GOG games are installed and import all of them automatically.

### Additional information

GOG Galaxy has this feature. Steam also does it automatically upon adding a library folder in the storage manager.

**Comment by yoshimo** [comment]
EpicGames currently does not offer this in their own launcher so it cannot be copied by Heroic.
You need to bring that up with Epic :)

**Comment by imLinguin** [comment]
Games doesn't have metadata in their game directories that can be used for such option I'm affraid

**Comment by TheOmninaut** [comment]
I went to add a suggestion for this feature and came across this. I can see how a library manager would be a better long term solution but couldn't there be an easily implemented solution for the time being? Especially since #1673 was made in 2022 and it still hasnt been made. 

What i mean is, if a gog game has been installed on a seperate drive using heroic, then later (on another pc or fresh OS install) each game can be reimported individually. It doesn't require meta data or anything to import and doesnt have any issues from my experience because it looks for the game files of that particular game. Also, when installing a game with heroic it creates a folder for that game that is named with the games name.

Wouldnt it be possible to just have a "check folder for installed games" option where the user points to a folder and it checks all the folders within that user pointed folder and checks the names to at least cross reference with the users library. then if it detects a folder that has the same name as one that heroic would use when installing a game it does the already implemented import task. 

To me, 90% of the work for this has already been done. You can import games already so yea youll probably not be able to import games that arent in your library, werent installed with heroic or if the folder name was changed. But at the very least something like this would be able to rediscover games that were installed with heroic until the library manager is made. As someone with over 500 gog games installed with heroic, the lack of this feature is a huge headache whenever i have to reimport every game 1 at a time.

**Comment by prehistoriccraftman** [comment]
Wrong answers from people, here...
Epic HAS an option to import ENTIRE folder : just specify it which folder.
Gog has same, Steam has same, EA has same, Origin has same.
ONLY heroic games launcher do NOT have while it is asked FOR YEARS, now. And YOU know it.
We are in 2026, the demand is still alive. You have closed for not planned in 2022. FOUR YEARS later, people STILL NEED AND ASK FOR IT !

**Comment by arielj** [comment]
Just curious, do you think we are not doing it because we don't want to? I want to understand what you think is happening to be sure what to answer to that really bad message

I feel you are assuming a lot of things there in your message, just want to be sure

**Comment by TheOmninaut** [comment]
> Just curious, do you think we are not doing it because we don't want to? 

I didnt mean to be argumentative or start a flame war here. Im just genuinely curious because i dont understand what the issue is. if you would be able to clarify thatd probably stop this from continuing to crop up.

Again, the import games from folder functionality already exists so why couldnt it be batched. Not to say it can, it just feels like this already exists so its confusing

(This isnt a code suggestion, i havent read the source or even know what parts use which language) to me it feels like it would be a simple script. 

Cd "~/Games/Heroic Games";
game_list = generate_array_or_something_to_assign_game_ids_to_library_count();

Loop (for # of games in library; i++;)
{
game_id = get_game_id(game_list(i))

If check_folder_exists(get_game_folder_name(game_id))
{run_currently_implemented_import_task(game_id);}
//else {do nothing, move onto next iteration or log failed to find game}
}

**Comment by arielj** [comment]
to be clear, my comment was not an answer to your comment but to the other user with that really bad attitude

I was not part of this thread when it was closed, but it's not closed saying "we won't do this ever" (I think the NOT PLANNED is just a bad label since github doesn't have that many options), the last message clearly says it can be done after other things are done first (we have discussed what is that "info" that needs to be there to batch import games in an efficient way)

yes, technically you loop over directories and check something, but what is that "something" is what's important, it's not easy to go over the technical details here (I also don't know all the details), but it has to work and work correctly, we can for example check folder names because users can change folder names, we can't assume that's the metadata to use, user also will want to mass import sideloaded games if they had some before I imagine, and then you have to make sure you do this efficiently, you don't want to loop for who knows how many folder (some users change the install folder to be at the root of a drive, then you might have a bunch more folder that you check that are unrelated to game, making this process super long), then you have to support mutiple platforms, and also you have to define a prefix when you import a windows game, would that info be stored as metadata with the game? or guessed during import? there's a lot of things going on and they all need to be addressed

we have discussed internally different steps we need to do before getting this to work because we have to consider more things and we have group of people who do this on our free time, and it's not like we have not done anything in years, we have done so many other things available time is finite

clearly none of us had the time to do what's needed to get this implemented (and nobody else has either outside of the main heroic team), so that should be a clear indication that it's not as simple as "loop and import"

to clarify, we ALSO want this feature, we are not saying it's technically impossible, what bothers me is that other comment that seems to imply that we don't care or that we haven't tried or that we don't listen to user and sounds like an entitled user demanding stuff (this is open source, literally anyone can contribute this feature if they figure out the right way to do it, and from the (guessing) probably thousands of Heroic users that might know how to code, nobody made this contribution)
