### ISSUE TITLE
Disable update notfication when Heroic is installed with package manager

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#1733]
### Problem description

To quote from the [changelog for version 2.4.0](url)

> Show available new versions (beta and stable) on the sidebar as well (except Flatpak)

This is great to have such a notification if the User uses e.g. a AppImage. But this is not needed for package manager like the AUR and should be disabled when they are used.

### Feature description

Maybe package maintainers could place a file in the directory Heroic is installed to indicate that it is installed with a package manager. This file could also contain a short text like e.g. "Installed from AUR" that could be shown somewhere in the GUI or in the logs.

**Comment by flavioislima** [comment]
It is disabled by default on Flatpak since we know when we are on a Flatpak but there is no way for Heroic to know if it was installed through AUR or another repository.
There is an option on General settings to disable this feature as well.

**Comment by JakobDev** [comment]
> but there is no way for Heroic to know if it was installed through AUR or another repository.

As I suggest above, package maintainers could place a file in the directory  Heroic is installed. If the File exists, Heroic nows it is managed by a package manager.

**Comment by flavioislima** [comment]
I think that if we encourage people to modify what we have in the Heroic install folder, we might lose control of it and people can add malicious code to that.
Right now we have 5 packages on AUR, for instance, 2 officials and 3 maintained by other people that we don't know. If they somehow add malicious code to it we would never know.

Officially we just distribute Heroic on Flatpak where I am the maintainer and AUR with the packages:
`heroic-games-launcher-bin` and `heroic-games-launcher-bin-beta`.

I believe the option to not check for new versions should suffice and would be one less thing for us to care about. 

In the end, the option might also be good even for the repository versions because if the 'not official maintainer' forget to update the repo with a new version, people could ping him for that once they get the notification.
