### ISSUE TITLE
Show information from howlongtobeat, areweanticheatyet and protondb

### ISSUE THREAD

**Issue by Verantor** [Heroic-Games-Launcher/HeroicGamesLauncher#1742]
### Problem description

I like to know when I am looking at a game how long I will need to play though. [howlongtobeat](https://howlongtobeat.com/)
(if exist) its status on [protondb](https://www.protondb.com/)
and data from [areweanticheat.net](https://areweanticheatyet.com/)

### Feature description

Pull data from [howlongtobeat](https://howlongtobeat.com/)
(if exist) its status on [protondb](https://www.protondb.com/)
and [areweanticheat.net](https://areweanticheatyet.com/)

**Comment by JakobDev** [comment]
areweanticheat is already included

**Comment by ScanuNicco** [comment]
Would love to see protondb status integrated directly into the library

**Comment by arielj** [comment]
We include a link to open protondb in the search result page in game page > tools.

I don't think it makes sense to actually show the info from protondb inside Heroic because:
- protondb is specific to steam (many epic games are not listed and many will be really hard to match since naming is not the same)
- protondb is specific to proton (reports from protondb won't always be correct since heroic users would probably be using wine-ge or crossover instead of proton)
- a game working in steam may not work in heroic (like epic games may be missing EAC runtime for example)
- there's too much information in protondb to actually show it inside Heroic (that's why I think the link is enough)

Info from areweanticheatyet shows up in the game's page and in the install dialog already.

We could maybe add a link to howlongtobeat if it's a feature requested by more users, but I wouldn't add more than a link to the search result page (again, hard to match if name is not consistent, a lot of information to fit inside the heroic UI)

**Comment by flavioislima** [comment]
I don't think adding how long to beat into the game info is relevant and will also be another api to request information and to maintain. Don't really see much value on this.

**Comment by flavioislima** [comment]
Reopening this one since I found this API here for How Long to Beat, it seems simple to implement it on the Game Page:
https://github.com/ckatzorke/howlongtobeat

**Comment by flavioislima** [comment]
Does this looks good? @arielj @Verantor 
![image](https://user-images.githubusercontent.com/26871415/202871376-18c92716-51de-4c0d-a447-ce92a79ee177.png)

**Comment by Verantor** [comment]
Sick it looks so good

**Comment by Maltavius** [comment]
> We include a link to open protondb in the search result page in game page > tools.
> 
> I don't think it makes sense to actually show the info from protondb inside Heroic because:
> 
>     * protondb is specific to steam (many epic games are not listed and many will be really hard to match since naming is not the same)
> 
>     * protondb is specific to proton (reports from protondb won't always be correct since heroic users would probably be using wine-ge or crossover instead of proton)
> 
>     * a game working in steam may not work in heroic (like epic games may be missing EAC files for linux for example)
> 
>     * there's too much information in protondb to actually show it inside Heroic (that's why I think the link is enough)
> 
> 
> Info from areweanticheatyet shows up in the game's page and in the install dialog already.
> 
> We could maybe add a link to howlongtobeat if it's a feature requested by more users, but I wouldn't add more than a link to the search result page (again, hard to match if name is not consistent, a lot of information to fit inside the heroic UI)

I'd want to be able to group all the games that I have into Platinum, Gold, Silver, Bronze etc. based on ProtonDB. Either that or Heroic would provide the same data based upon people installing games and playing them for more than 10% of Time to finish?
