### ISSUE TITLE
Notify the user of free unclaimed content and offers for wishlisted games

### ISSUE THREAD

**Issue by yoshimo** [Heroic-Games-Launcher/HeroicGamesLauncher#1837]
### Problem description

I'm always frustrated when i missed free gifts on my favoruite game stores

### Feature description

The official launchers have banners, notifications and the possibility to filter the store when dlcs for your games, content and complete games are for free for a while or your wishlisted entries are on sale.

We should inform the user in both cases so it is less likely to miss a good opportunity.

### Alternatives

EpicFreeGames Discord announce Bot

**Comment by flavioislima** [comment]
We don't really want to add those features to Heroic since
- It is not only an Epic games launcher
- Will make it bloated and show more info than needed
- It is already possible to check all of those if you go to the Epic store.
- will go against the concept of simplicity that we have

So we see no value on adding more things than needed because we don't want to be the Epic client, far from it :D
