### ISSUE TITLE
Skip login, show Library

### ISSUE THREAD

**Issue by LiamDawe** [Heroic-Games-Launcher/HeroicGamesLauncher#1936]
### Problem description

Testing the new pre-release again - https://discord.com/channels/812703221789097985/812703452085223434/1033742423970566294

Currently, you need to login to either Epic or GOG before you can view Library, this needs to be split for using Heroic for Wine installs.

Trying to work around it right now, you have to login to both, otherwise you can't select to view "All" your library. Say I just added Epic, then click Add Game and added a exe for Wine but I now can't see it in the list as it's only showing epic.

### Feature description

Two requests:

- Always have the Library view.

- Always have the show "All" view available.

**Comment by arielj** [comment]
I think we'll need to make it really clear for the users that they do need to login into epic or gog to see their games from those stores. Because I can imagine users opening heroic, seeing the empty library and clicking the `add game` button thinking that's where they add epic/gog games too if they are not familiar with Heroic yet.

Maybe we have to start in the Login screen and not showing the `Library` item in the sidebar (as it is now), but in the Login screen we can show an action to skip the login and only then enable the Library for not logged in users (and then it stays enabled). That way users can't go to the library without reading that information and they have to skip it explicitly and they know they can always go back to `Manage Accounts` to log in.

**Comment by LiamDawe** [comment]
Easiest way is probably just having the Login screen contain the logins as they are now, plus a big View Library addition button on the right. Along with always having Library available and Login on the left panel.

**Comment by flavioislima** [comment]
That's a good point @LiamDawe 
we will find a solution before the next beta, but it is complicated like Ariel said.
We will try this as you said and then collect some feedback and try to improve it before the stable release.

**Comment by flavioislima** [comment]
@LiamDawe 
feel free to test the latest build, should fix the issues you mentioned.

**Comment by redromnon** [comment]
This should be fixed.
