### ISSUE TITLE
Option to opt in/out Beta release/updates

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#2027]
### Problem description

Beta channel is famous for instability, and not everyone like beta release.

### Feature description

So far there is an option to check for heroic updates on Startup and I hope it will be expanded to allow/disallow beta channel. 

### Alternatives

Steam or GOG Galaxy

**Comment by flavioislima** [comment]
Actually, the idea is to offer beta release to stable users because we want for EVERYONE to test it. 
Also, we will never release a beta if it might break basic thinks like login, install and play, for instance.

The reason it is called beta is because it has NEW features that are not Stable or not completely finished and we would like to receive feedback about them so we can improve and make it stable before a new big release is out.

So we have no plans on adding such option for now since this would make us have less feedback on beta and the new Major release would be less stable and with less features 👍🏽
