### ISSUE TITLE
Full Screen Not Working

### ISSUE THREAD

**Issue by Hamish1066** [Heroic-Games-Launcher/HeroicGamesLauncher#2059]
### Describe the bug

My games show up in a smaller resolution than the screen

### Add logs

N/A

### Steps to reproduce

Play a game on Steam Deck

### Expected behavior

Full Screen

### System Information

- OS SteamOS
- Heroic Version 2.4.3

**Comment by arielj** [comment]
This is not Heroic's fault. We just tell wine/proton to run the game, I don't think we can have any control on the game's resolution. Some games on the steam deck detect the resolution wrong and you have to change it manually on the game's settings (not in heroic). I imagine it's because the steam deck's resolution is not one of the standard resolutions from other devices.
