### ISSUE TITLE
Launcher Connectivity issue

### ISSUE THREAD

**Issue by Tear4Pixelation** [Heroic-Games-Launcher/HeroicGamesLauncher#2098]
### Describe the bug

The launcher says I'm offline although I have perfect internet. Also when I launch a game, it says I'm not logged in to epic, but I logged in in the launcher.
This issue only occurs in 2.5 but the old 2.4.3 stopped working with the release of the new version.
Thank you for your time and have a great day!

### Add logs

```text
(15:07:03) INFO:    [Connection]:       Connectivity: check-online
(15:07:03) INFO:    [Connection]:       Pinging external endpoints
(15:07:03) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary --version
(15:07:03) INFO:    [Legendary]:        Legendary location: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary
(15:07:03) INFO:    [Gog]:              GOGDL location: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/gogdl
(15:07:04) WARNING: [Backend]:          Failed to register protocol with OS.
(15:07:04) INFO:    [Gog]:              Running command: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(15:07:04) INFO:    [Backend]:          

Heroic Version: 2.5.0 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Ubuntu KERNEL: 5.15.0-52-generic ARCH: x64
CPU: Intel Core™ i7-3770K @3.5 GOVERNOR: schedutil
RAM: Total: 23.43 GiB Available: 20.34 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1050 Ti VRAM: 4036MB DRIVER: 470.141.03 
PROTOCOL: x11

(15:07:05) INFO:    [Backend]:          Checking for new Heroic Updates
(15:07:05) INFO:    [Connection]:       All ping requests failed:
(15:07:05) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:07:05) INFO:    [Backend]:          Checking for current version changelog
(15:07:05) INFO:    [Frontend]:         Refreshing Library
(15:07:05) INFO:    [Legendary]:        Refreshing library...
(15:07:05) INFO:    [Legendary]:        Refreshing Epic Games...
(15:07:05) INFO:    [Legendary]:        Game list updated, got 12 games & DLCs
(15:07:05) WARNING: [DXVKInstaller]:    App offline, skipping possible DXVK update.
(15:07:10) INFO:    [Connection]:       Pinging external endpoints
(15:07:12) INFO:    [Connection]:       All ping requests failed:
(15:07:12) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:07:15) INFO:    [Frontend]:         Refreshing Library
(15:07:15) INFO:    [Legendary]:        Refreshing library...
(15:07:15) INFO:    [Legendary]:        Refreshing Epic Games...
(15:07:15) INFO:    [Legendary]:        Game list updated, got 12 games & DLCs
(15:07:22) INFO:    [Connection]:       Pinging external endpoints
(15:07:24) INFO:    [Connection]:       All ping requests failed:
(15:07:24) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:07:39) INFO:    [Connection]:       Pinging external endpoints
(15:07:41) INFO:    [Connection]:       All ping requests failed:
(15:07:41) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:08:01) INFO:    [Connection]:       Pinging external endpoints
(15:08:03) INFO:    [Connection]:       All ping requests failed:
(15:08:03) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:08:28) INFO:    [Connection]:       Pinging external endpoints
(15:08:30) INFO:    [Connection]:       All ping requests failed:
(15:08:30) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:09:00) INFO:    [Connection]:       Pinging external endpoints
(15:09:02) INFO:    [Connection]:       All ping requests failed:
(15:09:02) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:09:16) ERROR:   [Backend]:          Failed to get epic service status with Error: connect ETIMEDOUT 0.0.31.144:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
(15:09:16) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:09:16) ERROR:   [Backend]:          Error when checking for Heroic updates Error: connect ETIMEDOUT 0.0.31.144:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
(15:09:16) ERROR:   [Backend]:          Error when checking for current Heroic changelog
(15:09:24) ERROR:   [Backend]:          Failed to get epic service status with Error: connect ETIMEDOUT 0.0.31.144:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
(15:09:24) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(15:09:37) INFO:    [Connection]:       Pinging external endpoints
(15:09:39) INFO:    [Connection]:       All ping requests failed:
(15:09:39) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:10:19) INFO:    [Connection]:       Pinging external endpoints
(15:10:21) INFO:    [Connection]:       All ping requests failed:
(15:10:21) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:11:06) INFO:    [Connection]:       Pinging external endpoints
(15:11:08) INFO:    [Connection]:       All ping requests failed:
(15:11:08) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:11:58) INFO:    [Connection]:       Pinging external endpoints
(15:12:00) INFO:    [Connection]:       All ping requests failed:
(15:12:00) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:12:55) INFO:    [Connection]:       Pinging external endpoints
(15:12:57) INFO:    [Connection]:       All ping requests failed:
(15:12:57) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:13:57) INFO:    [Connection]:       Pinging external endpoints
(15:13:59) INFO:    [Connection]:       All ping requests failed:
(15:13:59) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:15:04) INFO:    [Connection]:       Pinging external endpoints
(15:15:06) INFO:    [Connection]:       All ping requests failed:
(15:15:06) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:15:13) INFO:    [Backend]:          Launching Paladins (Antbird)
(15:15:13) INFO:    [Backend]:          Preventing display from sleep
(15:15:13) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-5.0.3 (Ubuntu 5.0.3-3ubuntu2)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:15:13) DEBUG:   [Backend]:          Running Wine command: wineboot --init
(15:15:17) ERROR:   [Backend]:          Couldn't find all library folders of Wine Default - wine-5.0.3 (Ubuntu 5.0.3-3ubuntu2)!
Missing undefined and/or undefined!
Falling back to system libraries!
(15:15:17) INFO:    [Legendary]:        Running command: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary launch Antbird --json --offline
(15:15:17) INFO:    [Legendary]:        Launching Paladins: LD_PRELOAD= WINEPREFIX=/home/jan/Games/Heroic/Prefixes/Paladins ORIG_LD_LIBRARY_PATH=/tmp/.mount_HeroicA3zkh6/usr/lib: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary launch Antbird --language en --offline --wine /usr/bin/wine
(15:16:09) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(15:16:09) INFO:    [Frontend]:         Refreshing Library
(15:16:09) INFO:    [Legendary]:        Refreshing library...
(15:16:09) INFO:    [Legendary]:        Game list updated, got 12 games & DLCs
(15:16:09) INFO:    [Frontend]:         Refreshing Library
(15:16:09) INFO:    [Legendary]:        Refreshing library...
(15:16:09) INFO:    [Legendary]:        Game list updated, got 12 games & DLCs
(15:16:16) INFO:    [Connection]:       Pinging external endpoints
(15:16:18) INFO:    [Connection]:       All ping requests failed:
(15:16:18) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:17:34) INFO:    [Connection]:       Pinging external endpoints
(15:17:36) INFO:    [Connection]:       All ping requests failed:
(15:17:36) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:18:56) INFO:    [Connection]:       Pinging external endpoints
(15:18:58) INFO:    [Connection]:       All ping requests failed:
(15:18:58) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:20:23) INFO:    [Connection]:       Pinging external endpoints
(15:20:25) INFO:    [Connection]:       All ping requests failed:
(15:20:25) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:21:38) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: /tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/jan/Games/Heroic/Prefixes/rocketleague
(15:21:38) INFO:    [Legendary]:        Getting more details with 'legendary info'
(15:21:38) INFO:    [Legendary]:        Getting more details with 'legendary info'
(15:21:38) INFO:    [Legendary]:        Abort command "/tmp/.mount_HeroicA3zkh6/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix /home/jan/Games/Heroic/Prefixes/rocketleague"
(15:21:44) INFO:    [Shortcuts]:        Prepare Steam images for Rocket League®
(15:21:45) INFO:    [Shortcuts]:        Rocket League® was successfully added to Steam.
(15:21:52) INFO:    [Shortcuts]:        Remove Steam images for Rocket League®
(15:21:52) INFO:    [Shortcuts]:        Rocket League® was successfully removed from Steam.
(15:21:56) INFO:    [Connection]:       Pinging external endpoints
(15:21:58) INFO:    [Connection]:       All ping requests failed:
(15:21:58) INFO:    [Connection]:       AggregateError: All promises were rejected
(15:21:58) ERROR:   [Backend]:          Was not able to get HowLongToBeat data Error: Error: timeout of 20000ms exceeded
    at HltbSearch.<anonymous> (/tmp/.mount_HeroicA3zkh6/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (/tmp/.mount_HeroicA3zkh6/resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

It should launch the game like normal, without the "no account Issue"

### Screenshots

![Prob heroic](https://user-images.githubusercontent.com/104512895/204552958-02e4d540-2a57-4f0c-8a8b-c6b3c56ecc87.png)

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 22.04
- Heroic Version [e. g. 2.1.1]: 2.5

**Comment by flavioislima** [comment]
Are you using any type of proxy?
Because on the logs I can see that even the calls that do not check online connectivity like the HowLongToBeat data are failing. So something is in between Heroic and the internet.

**Comment by Helsching** [comment]
Hello, I am having the same problem since 2.5.0. I am connected to the internet. I can browse EPIC and GOG stores just fine.

Log:

(19:36:53) INFO:    [Connection]:       Connectivity: check-online
(19:36:53) INFO:    [Connection]:       Pinging external endpoints
(19:36:53) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(19:36:53) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(19:36:53) INFO:    [Gog]:              GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(19:36:53) WARNING: [Backend]:          Protocol already registered.
(19:36:53) INFO:    [Gog]:              Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl --version
(19:36:54) INFO:    [Backend]:          

Heroic Version: 2.5.0 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: ManjaroLinux KERNEL: 6.1.0-1-MANJARO ARCH: x64
CPU: AMD Ryzen 5 5600G with Radeon Graphics @3.5 GOVERNOR: schedutil
RAM: Total: 15.42 GiB Available: 13.01 GiB
GRAPHICS: GPU0: Navi 23 [Radeon RX 6600/6600 XT/6600M] VRAM: 1MB  
PROTOCOL: x11

(19:36:54) INFO:    [Backend]:          Checking for new Heroic Updates
(19:36:54) INFO:    [Backend]:          Checking for current version changelog
(19:36:54) INFO:    [Frontend]:         Refreshing Library
(19:36:54) INFO:    [Legendary]:        Refreshing library...
(19:36:54) INFO:    [Legendary]:        Refreshing Epic Games...
(19:36:54) INFO:    [Legendary]:        Game list updated, got 59 games & DLCs
(19:36:55) INFO:    [Connection]:       All ping requests failed:
(19:36:55) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:36:56) WARNING: [DXVKInstaller]:    App offline, skipping possible DXVK update.
(19:36:59) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(19:37:00) INFO:    [Connection]:       Pinging external endpoints
(19:37:02) INFO:    [Connection]:       All ping requests failed:
(19:37:02) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:37:12) INFO:    [Connection]:       Pinging external endpoints
(19:37:14) INFO:    [Connection]:       All ping requests failed:
(19:37:14) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:37:29) INFO:    [Connection]:       Pinging external endpoints
(19:37:31) INFO:    [Connection]:       All ping requests failed:
(19:37:31) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:37:51) INFO:    [Connection]:       Pinging external endpoints
(19:37:53) INFO:    [Connection]:       All ping requests failed:
(19:37:53) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:38:18) INFO:    [Connection]:       Pinging external endpoints
(19:38:20) INFO:    [Connection]:       All ping requests failed:
(19:38:20) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:38:50) INFO:    [Connection]:       Pinging external endpoints
(19:38:52) INFO:    [Connection]:       All ping requests failed:
(19:38:52) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:39:27) INFO:    [Connection]:       Pinging external endpoints
(19:39:29) INFO:    [Connection]:       All ping requests failed:
(19:39:29) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:40:10) INFO:    [Connection]:       Pinging external endpoints
(19:40:12) INFO:    [Connection]:       All ping requests failed:
(19:40:12) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:40:57) INFO:    [Connection]:       Pinging external endpoints
(19:40:59) INFO:    [Connection]:       All ping requests failed:
(19:40:59) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:41:49) INFO:    [Connection]:       Pinging external endpoints
(19:41:51) INFO:    [Connection]:       All ping requests failed:
(19:41:51) INFO:    [Connection]:       AggregateError: All promises were rejected
(19:42:46) INFO:    [Connection]:       Pinging external endpoints
(19:42:48) INFO:    [Connection]:       All ping requests failed:

Screenshot:

![image](https://user-images.githubusercontent.com/119527541/204872085-40c9b524-6adb-475e-a91e-52a9fd73f3d0.png)

**Comment by arielj** [comment]
Can you confirm if you are using any kind of proxy?

**Comment by arielj** [comment]
just wondering, do you have a rather slow connection? because we ping 3 different sites and stop the request after 2 seconds, it looks like the sites are not responding fast enough

we ping https://github.com, https://store.epicgames.com and https://gog.com and from your comments you seem to have access to those sites just fine?

**Comment by flavioislima** [comment]
@arielj do you think that could be fixed if we put the initial state as connected and then do an initial check after the frontend is ready?

**Comment by arielj** [comment]
I think I originally was handling this after the frontend was ready, but there are things that happen before that that would break if there's no connection (like the DXVK update, the check for updates, etc) so I had to move that to the backend really early

the problem with assuming connectivity is that we would let those things go through and fail if there's no connectivity

I imagine 3 ideas:
- first I can increase the timeout from 2s to 5s or 10s in case it's some slow connection issue
- I can add an `ignore/dismiss` button to tell Heroic `stop checking this and assume I'm connected` that stays there until the next disconnect is detected
- I can add a config to turn this connectivity check's off in the advanced settings

**Comment by arielj** [comment]
I'll try to implement some of these changes tonight

**Comment by Helsching** [comment]
> just wondering, do you have a rather slow connection? because we ping 3 different sites and stop the request after 2 seconds, it looks like the sites are not responding fast enough, I see all the pings are failing exactly after those 2 seconds:
> 
> ```
> (19:41:49) INFO: [Connection]: Pinging external endpoints
> (19:41:51) INFO: [Connection]: All ping requests failed:
> ```
> 
> we ping https://github.com, https://store.epicgames.com and https://gog.com and from your comments you seem to have access to those sites just fine?

I ping the same sites and they are working. They do seem to take some time to resolve though:

[jason@HAL ~]$ ping https://github.com/
ping: https://github.com/: Name or service not known
[jason@HAL ~]$ ping github.com
PING github.com (140.82.121.3) 56(84) bytes of data.
64 bytes from lb-140-82-121-3-fra.github.com (140.82.121.3): icmp_seq=1 ttl=52 time=47.5 ms
64 bytes from 3.121.82.140.in-addr.arpa (140.82.121.3): icmp_seq=2 ttl=52 time=47.9 ms
64 bytes from 3.121.82.140.in-addr.arpa (140.82.121.3): icmp_seq=3 ttl=52 time=48.3 ms
64 bytes from 3.121.82.140.in-addr.arpa (140.82.121.3): icmp_seq=4 ttl=52 time=48.2 ms
^C
--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 47.544/47.994/48.318/0.301 ms
[jason@HAL ~]$ ping store.epicgames.com
PING store.epicgames.com(2606:4700::6812:59f (2606:4700::6812:59f)) 56 data bytes
64 bytes from 2606:4700::6812:59f (2606:4700::6812:59f): icmp_seq=1 ttl=59 time=10.5 ms
64 bytes from 2606:4700::6812:59f (2606:4700::6812:59f): icmp_seq=2 ttl=59 time=10.6 ms
64 bytes from 2606:4700::6812:59f (2606:4700::6812:59f): icmp_seq=3 ttl=59 time=10.8 ms
^C64 bytes from 2606:4700::6812:59f: icmp_seq=4 ttl=59 time=10.6 ms

--- store.epicgames.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 8999ms
rtt min/avg/max/mdev = 10.539/10.629/10.765/0.086 ms
[jason@HAL ~]$ ping www.gog.com
PING e11072.b.akamaiedge.net (2.21.52.132) 56(84) bytes of data.
64 bytes from a2-21-52-132.deploy.static.akamaitechnologies.com (2.21.52.132): icmp_seq=1 ttl=58 time=38.5 ms
64 bytes from 132.52.21.2.in-addr.arpa (2.21.52.132): icmp_seq=2 ttl=58 time=38.6 ms
64 bytes from 132.52.21.2.in-addr.arpa (2.21.52.132): icmp_seq=3 ttl=58 time=39.4 ms
64 bytes from 132.52.21.2.in-addr.arpa (2.21.52.132): icmp_seq=4 ttl=58 time=38.8 ms
^C
--- e11072.b.akamaiedge.net ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3006ms
rtt min/avg/max/mdev = 38.538/38.833/39.387/0.338 ms

**Comment by Helsching** [comment]
My previous comment with respect to the slow initial resolve of the sites led me to try and change DNS server to 1.1.1.1 (was automatic for ipv4 and 8.8.8.8 for ipv6), and the issue was resolved.

So what probably happened, at least in my case was that the 2 seconds to resolve the 3 sites (github, gog, epic) was not enough, resulting in perpetual offline status.

**Comment by Tear4Pixelation** [comment]
At me it didn't change, only that I could Ignore the status

**Comment by Tear4Pixelation** [comment]
> just wondering, do you have a rather slow connection? because we ping 3 different sites and stop the request after 2 seconds, it looks like the sites are not responding fast enough, I see all the pings are failing exactly after those 2 seconds:
> 
> ```
> (19:41:49) INFO: [Connection]: Pinging external endpoints
> (19:41:51) INFO: [Connection]: All ping requests failed:
> ```
> 
> we ping https://github.com, https://store.epicgames.com and https://gog.com and from your comments you seem to have access to those sites just fine?
Well my internet connection is fine, definitely faster than 2 s.
