### ISSUE TITLE
Proton Next is gone & it should merged to Proton 7.0.5

### ISSUE THREAD

**Issue by dtantono** [Heroic-Games-Launcher/HeroicGamesLauncher#2154]
### Describe the bug

I remembered that you added Proton Next as a preview for Proton 7.0.5. But, now Proton next reach stable and it is gone. So, it will be better for Heroic to follow it as well to prevent inconsistency and confusion between users. 

### Add logs

```text
it is too long and I added it on additional comment
```

### Steps to reproduce

1. Go to game
2. Click on download button
3. Scroll down to Wine version
4. Proton next is there

### Expected behavior

Proton next is gone and it should be merged with proton 7.0.5

### Screenshots

![image](https://user-images.githubusercontent.com/29157187/206125976-d9785969-061c-4d33-94f9-9dbd884fa56f.png)
![2022-12-07_17-19](https://user-images.githubusercontent.com/29157187/206126780-c204650a-f296-4ab6-ab5d-a4252ed0db07.png)

### System Information

- OS [e. g. "Ubuntu"]: Ubuntu 22.04
- Heroic Version [e. g. 2.1.1]: 2.5.1

### Additional information

https://linuxgamingcentral.com/posts/proton-7.0-5/
[Log.zip](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10174097/Log.zip)

**Comment by arielj** [comment]
The information in that select/dropdown is generated reading the user's installed protons/wines in different locations. To remove Proton Next from there it's just a matter of deleting the right folder.

I'm closing this since it's really old and it's something that users have to do manually, not something we need to handle with code.
