### ISSUE TITLE
PPA (Preferably) or Deb Repo

### ISSUE THREAD

**Issue by InklingGirl** [Heroic-Games-Launcher/HeroicGamesLauncher#2322]
### Problem description

There is currently no way to install Heroic & keep it up-to-date using Ubuntu's native package manager `apt` since the app's removal from Raul Dipeas' Deb repo. Ubuntu & other Debian-derived distro users have to to do a one-&-done installation from the .deb release & manually re-download or write a script to do so, or rely on pseudo-sandboxed cross-distro formats like Flatpak.

### Feature description

Preferably a PPA on [launchpad.net](https://launchpad.net/), or a first-party (or another third-party) Deb repo.

### Alternatives

A provided updater script.

### Additional information

Are there plans to bring back this kind of support?

**Comment by Nocccer** [comment]
Not going to happen from heroic side. 
We would need a ppa repository. I think that costs money and is another thing we need to maintain.
Using Flatpak for auto update is the best choice imo.

**Comment by InklingGirl** [comment]
I'm currently too inexperienced to even know where to begin w/ that, or even setting up a rudimentary Deb repo myself, & I probably won't have the time for a bit.

Is there any stated reason for its absence from the third-party repo? Any chance that it could be restored on his or another's end? I'd do something from a VPS if I had the time to look into it.

**Comment by flavioislima** [comment]
I tried that in the past and it is far from easy. Adding to official repos is even more difficult, especially for an electron app.

So it is totally out of question. Best you can do is to use the Flatpak since it will be more stable and easier to debug simply because it is the same on all platforms, no matter the distro. 

In the future, Flatpak might be the only way of installing Heroic, we might consider that because it is a lot of work to maintain such a high number of packages and distros for us.
