### ISSUE TITLE
Add a faster `Install with defaults` button to install games

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#2344]
### Problem description

When installing multiple games, you have to click Install, wait a few seconds until some install info is fetched, just to continue and enqueue the game. In most cases (in my experience), you don't really need to change things here and you may already know you have enough disk space to install the games you want.

### Feature description

An option (maybe in the right click menu) to add the game to the queue with the default values that the dialog would show, so we don't have to wait.

**Comment by imLinguin** [comment]
We still need to fetch languages for GOG games. Keep that in mind

**Comment by arielj** [comment]
I understand we still have to fetch the information when actually installing the game, right? in that case we could default to whatever `english` the game info has for a given game maybe?

**Comment by imLinguin** [comment]
Or even try to get the language user has set in Heroic. And fallback to `en`, `en-US` etc as default

**Comment by flavioislima** [comment]
Hmm, one more feature that HEroic used to have on version 1.0 and we have removed.
On Heroic 1.x we had a select on the game page and the first option was to install using the defaults, so default installs path and default wine settings.

Since we have removed this select we have never added it again.
But I agree, it is useful, but tricky when you have games that has support for multiple platforms and multiple languages, DLCs and SDLs.

How to handle these case? Should we skip games that have DLCs and SDLs to be installed with defaults?
What about platform? always use native? always use language set on Heroic?

Back then HEroic was more simple and did not any of those features, now having something like this requires a lot of logic and checks. And still something can go wrong.

One idea is perhaps open the install dialog and have a checkbox to use defaults, instead of just having it for wine, but use it for Path + wine settings.

But the user still needs to select the platform and everything else.

**Comment by arielj** [comment]
I think the feature should be kept simple, it should just set whatever is the default when you open the normal Install dialog (no dlcs selected, no sdl, Windows as a platform, etc) without any extra logic. And it should be clear for a user that if ANY tweaking is needed (like a specific platform / language) then they should use the normal dialog.

I have to say that my main issue is that most of the times I don't have multiple platforms or DLCs or SDLs or languages to chose and I still have to wait for the download size fetch and space calculations, then I click Install.

Maybe we can do something like, instead of disabling the install button we do:
- if it's still calculating sizes, show a dialog saying `we are calculating stuff, are you sure? Yes / No` and we just eneque the game without waiting
- if it finished calculating stuff we show no dialog

That should fix the issue of waiting but also warn the users that clicked there by mistake.

**Comment by arielj** [comment]
Closing this, I only thought about this when I was testing all my library and I was installing games consistently, in normal daily usage this is not that big of a deal.
