### ISSUE TITLE
[Linux/macOS] Auto Download and Instalation of Wine-GE/Wine-Crossover when no Wine was found

### ISSUE THREAD

**Issue by allora** [Heroic-Games-Launcher/HeroicGamesLauncher#2356]
### Problem description

I've noticed over time, that many people come to the support channels with some wildly misconfigured wine prefix, or wine itself. This happens for a variety of reasons, some of it ignorance on the user's part (pushing buttons they dont understand), some of it oddities when switching wine versions with the default system wine, if it exists. However it happens, the problem is usually users have very little understanding of any of this as most are very new to linux as a whole.

### Feature description

I'm proposing that heroic on first boot after install, asks the user what prefix should be set as default, using as simple to understand language as possible, on discord its been suggested to even just use a default, like Wine-GE. 

Additionally, the fact that after heroic resets, or deletion of the config files, the game's prefix could be reset to ~/.wine seems problematic. I wonder if there are solutions to this that dont cause more problems configuration wise.

### Additional information

I don't have a perfect solution to this, but my hope was to help address/get rolling, what I have been seeing lots of lately in the support forum.

**Comment by Etaash-mathamsetty** [comment]
I think it might be a good idea to only default to wine-ge if there is no system wine installed or if heroic is being run under flatpak, in my experience wine staging is simply better since it's able to open links in the system's browser (unlike wine-ge) and is running under a newer version of upstream wine, which generally has better compatibility than wine-ge, this will change with the release of proton 8.0, but atm I prefer having wine-staging as the default.

**Comment by flavioislima** [comment]
Yes, the idea is to use that when no wine was found OR the wine version is too old. Like some people sometimes has wine 6 installed on the machine.

I think this might be beneficial for macOS as well once we find a way to download and install wine for it as well.

**Comment by arielj** [comment]
Closing, this is already implemented
