### ISSUE TITLE
Better MacOS support: Native games, etc.

### ISSUE THREAD

**Issue by LukeVader-IV** [Heroic-Games-Launcher/HeroicGamesLauncher#246]
**Is your feature request related to a problem? Please describe.**
Wine already has MacOS support and currently there's no good option to play games like Rocket league on the platform

**Describe the solution you'd like**
A port of this application for MacOS users

**Additional context**
I have no clue If this would be hard to achieve but I think it would be appreciated by the MacOS crowd.
PS: I love the project, makes gaming on Linux that much better, keep it up (:

**Comment by adityaruplaha** [comment]
You'll be happy to hear that Heroic might just already work out of the box. We would greatly appreciate it if you could run it on macOS and let us know where things start going wrong. You might need to build it yourself to see the app crash dialogs.

**Comment by flavioislima** [comment]
Hi. There is no way to support mac right now since legendary doesn't work on mac. And heroic depend on it to login, download the games and launch them.

**Comment by entaromia** [comment]
@flavioislima I managed to run heroic on mac os. Nearly all features are working after some fixes.

![Heroic on mac](https://user-images.githubusercontent.com/30384045/111902666-9ada9d80-8a4f-11eb-98b8-1e1ba7f395d0.png)

Only cancelling game installation isn't working for now, it continues to download on background.

**Comment by flavioislima** [comment]
Nice, and for some reason Legendary is working. 
So you can login and download games?
So, I know legendary can download the Mac versions of the games that supports it.
The question is: download the native games when there is any or download the windows version and run with wine, even though the compatibility is not that good.

@entaromia I'll reopen this issue then.

**Comment by entaromia** [comment]
Yes, even there are no references to mac on legendary readme, it just works. I can login, download games, launch them using wine etc. Since now heroic works on mac, i will try to implement downloading native versions on mac today.

**Comment by flavioislima** [comment]
> Yes, even there are no references to mac on legendary readme, it just works. I can login, download games, launch them using wine etc. Since now heroic works on mac, i will try to implement downloading native versions on mac today.

Nice to hear! 
I know there is a flag to pass the OS version that you want to download. Would be good to have a filter on heroic to show only native versions.

**Comment by adityaruplaha** [comment]
>legendary doesn't work on mac

It does. No official support maybe, but the code does seem to support Mac.
Sorry I didn't notice this issue got closed.

**Comment by adityaruplaha** [comment]
> Only cancelling game installation isn't working for now

I would've into it, but I don't have a Mac to test against :/

**Comment by entaromia** [comment]
> > Only cancelling game installation isn't working for now
> 
> I would've into it, but I don't have a Mac to test against :/

It's a legendary issue on Mac as I can see, it also happens when you download from cli and send ```pkill -f  game name ```
Only way to stop with signals is killing legendary directly which will stop all installations.
Will look a better way when I finish adding downloading native version support.

**Comment by adityaruplaha** [comment]
> It's a legendary issue

I think you should file an issue on their GitHub too.

Also here's how to changle the platform:
https://github.com/derrod/legendary/blob/main/legendary/cli.py#L1245

**Comment by entaromia** [comment]
Yes, I will file an issue and wait some time before changing that.

>  > Also here's how to changle the platform:
> https://github.com/derrod/legendary/blob/313323e43a05eed57574977367fa7300bed26560/legendary/cli.py#L1247
I'm also using it to download. I'm pretty close to finish my tests and start implementing code wise.

**Comment by LukeVader-IV** [comment]
> I think you should file an issue on their GitHub too.

There's already an issue on the GitHub that was quickly disregarded by the project leader.

PS: the reason I didn't respond at first is because I didn't have any means of testing it. Glad to hear it already mostly works

**Comment by entaromia** [comment]
So it turns out it's not that easy to add native version support, because legendary does not add game to installed.json if you change the platform.
Which will make me need to add game to list manually. 

Also legendary thinks your game is out of date every time, because mac versions of games have a different prefix at the end of version like *gameVersion*-OSX or *gameVersion*-M.

I think we should separate it for now, adding mac support first and supporting native versions later. It is definitely possible but will take some time.
If it's alright, i will open a pull request to do the first part.

**Comment by joex92** [comment]
hello, how do I install this on MacOS?

**Comment by adityaruplaha** [comment]
Build it yourself. We don't provide prebuilts for macOS yet.

**Comment by adityaruplaha** [comment]
There's instructions on the README. Please go through them, and if you still have issues, please ask on our Discord server.

**Comment by flavioislima** [comment]
Unfortunately, I'll need to close this ticket after some tests I did with legendary on mac.
I don't know if @LukeVader-IV and @entaromia tried to download a native MacOS game with legendary. It downloads ok so I was thinking about doing the install management on Heroic side since Legendary doesn't do that.

But the games downloaded using Legendary doesn't run. At least if I call them directly, so Legendary doesn't support mac and can't run the native game. Games that have DRM won't work and even the ones that are DRM free doesn't work either.
I was about to work on a filter on Macs to show only native games and install them on the Applications folder, and store a command to call them directly from Heroic.

Can your try on your side, guys? Otherwise, let's close this one and focus on other improvements for the platform.
