### ISSUE TITLE
Global Sync Save option

### ISSUE THREAD

**Issue by zeroxoneafour** [Heroic-Games-Launcher/HeroicGamesLauncher#249]
It would be nice if there was a way to automatically enable sync saves for all installed games that support it, so I don't have to go in and manually change the setting myself. The individual game sync save options would have another option, `default`, which would set it to the default global value. When a game is first installed, the sync save option would be set to default.

**Comment by zeroxoneafour** [comment]
If the save directory cannot be auto detected, pop up a menu after installation of an app

**Comment by flavioislima** [comment]
I don't think is a good idea to globally enable the sync saves. Some games, even after the autodetect, gets the wrong path. Torchlight 2 for instance. Heroic detects the right path in terms of names, but some words are capitalised and since Linux is a case sensitive OS, it doesn't get the correct save path.

I think this would lead to more bugs.

The idea about being per game is that the user checks the save path yourself and fix it if it is not correct.
