### ISSUE TITLE
Fortnite - size of Game Installation

### ISSUE THREAD

**Issue by matchuek** [Heroic-Games-Launcher/HeroicGamesLauncher#2492]
### Describe the bug

''¯\_(ツ)_/¯''

![grafik](https://user-images.githubusercontent.com/40257309/221295405-f6441e08-9a59-42ba-99d6-d80abdd90511.png)
![grafik](https://user-images.githubusercontent.com/40257309/221296002-1eb5d4c2-f567-43cc-89c5-5feb59ca9a8d.png)

### Add logs

```text
please see upon
```

### Steps to reproduce

1. Install Fortnite
2. wait for update incoming (around 1 week as of today)
3. Install Update
4. See wrong size of installation

### Expected behavior

display of real used disk space

### Heroic Version

Latest Stable

### System Information

Heroic Version: 2.6.2 Trafalgar Law

Legendary Version:  0.20.32 Dark Energy (hotfix #6)

GOGdl Version: 0.6

Electron Version: 22.2.0

Chrome Version: 108.0.5359.215

NodeJS Version: 16.17.1

OS: Microsoft Windows 10 Home KERNEL: 10.0.19045 ARCH: x64

CPU: Intel Core™ i5-5200U @2.2 

RAM: Total: 15.92 GiB Available: 12.55 GiB

GRAPHICS: GPU0: Intel(R) HD Graphics 5500 VRAM: 1024MB  GPU1: NVIDIA GeForce GTX 950M VRAM: 4096MB DRIVER: 527.37

**Comment by matchuek** [comment]
maybe that's the whole trick:  #2514

**Comment by arielj** [comment]
I think this is fixed?

I just tried installing fornite and I see this:

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/3dc768fb-0aa3-4d87-99b7-e8f95ba5210d)

**Comment by matchuek** [comment]
I'm sorry, but I can't confirm:

![grafik](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/40257309/a148c3d4-cefb-4d12-8bf6-619fcba83202)

This happens after an update for the game is installed.

**Comment by arielj** [comment]
This seems to be an issue with Legendary, I updated it and the incorrect install size is in legendary's files and we read that from there (legendary seems to have a couple of issues handling fornite form what I read on discord).

I think it makes more sense for this to be fixed on legendary's side, I don't think it's something critical to justify changing code just to adapt to fornite.

The solution in that PR is still not good because it doesn't take into account what's actually installed and the change is done for all games, so if I have a game installed with dlcs and the number we show is correct, with that change it would be wrong.

One could argue it's actually worse because the number will look right when it's not (currently it looks wrong and it's wrong, which is good because it doesn't make the user believe that's the actual size).

If we want to add a proper workaround on heroic's side that works for all games we should actually get the size of the game folder after the installation is done and store that info. Then it would be the real installed size and not metadata from other places
