### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by niksingh710** [Heroic-Games-Launcher/HeroicGamesLauncher#2615]
### Describe the bug

Throws login error even though the login was successful

### Add logs

```text
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.common.authentication.authentication_failed
[Core] WARNING: Resuming failed due to invalid credentials: InvalidCredentialsError('errors.com.epicgames.common.authentication.authentication_failed')[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary/cli.py", line 3061, in <module>
File "legendary/cli.py", line 2972, in mainFile "legendary/cli.py", line 199, in list_games
File "legendary/core.py", line 403, in get_game_and_dlc_list
File "legendary/core.py", line 349, in get_assets
File "legendary/api/egs.py", line 171, in get_game_assets
File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
[2757331] Failed to execute script 'cli' due to unhandled exception!
```

### Steps to reproduce

The logging in process works fine but going to library shows a popup with this log.

### Expected behavior

Should list games.

### Heroic Version

Latest Stable

### System Information

- Arch linux
- latest bin package is used.

**Comment by 200433zc** [comment]
An error has occurred! Try to Logout and Login on your Epic account.
Available games:
* ARK: Survival Evolved (App name: aafc587fbf654758802c8e41e4fb3255 | Version: 357.9.win)
* Destiny 2 (App name: 592c359fb0e0413fb46dee2d24448eb4 | Version: 8374233)
* Dishonored - Definitive Edition (App name: d2da64bd4c4e422da4b1a88041492a3a | Version: 1.6)[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>
File "legendary\cli.py", line 2980, in main
File "legendary\cli.py", line 239, in list_games
UnicodeEncodeError: 'gbk' codec can't encode character '\xae' in position 13: illegal multibyte sequence
[11552] Failed to execute script 'cli' due to unhandled exception!

**Comment by Maltavius** [comment]
I get a similar thing with Dying Light.

I'm unable to use the Epic Login because it says the Captcha results are bad. It did work with logging in through Steam though

**Comment by ximian** [comment]
Seems to be the same issue as [#2590 ](url=https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2590)

**Comment by turbo25** [comment]
Having the same issue, logging in successfully on Epic, then Heroic throws this error about re-logging in back; tried it but with no luck.
Heroic 2.7.1
SteamOS Beta (3.4.6) on Steam Deck

**Comment by zShxck720** [comment]
I am having the same issue. is there a fix?

**Comment by ximian** [comment]
> I am having the same issue. is there a fix?

According to [this comment](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2590#issuecomment-1571631755), the problem lays down in the [Legendary](https://github.com/derrod/legendary) and already has been [fixed](https://github.com/derrod/legendary/commit/8b2809779f94caee24b5ddc0464e744bf776527e).

You can try [downloading the binary](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2590#issuecomment-1571864480) and setting it in Advanced settings in Heroic.

**Comment by karhima** [comment]
Getting the same error now after updating to 2.9.1 on Windows.
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Checking for updates...[Core] INFO: Getting authentication token...[cli] INFO: Launching 4d0ff75b922447649057c237c0bd1545...Traceback (most recent call last):
File "legendary\cli.py", line 3137, in <module>File "legendary\cli.py", line 3052, in main
File "legendary\cli.py", line 704, in launch_game
File "subprocess.py", line 951, in __init__
File "subprocess.py", line 1420, in _execute_childFileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
[10836] Failed to execute script 'cli' due to unhandled exception!

I already logged into Epic twice, I downloaded the latest legendary. exe and set it in advanced settings, nothing works. I really love this project, but this week was bad. First no game would launch due to that wrapper bug and now this. What else can I try?

**Comment by Own3dM3** [comment]
install proton - proton - GE - latest

**Comment by arielj** [comment]
Can anyone try with the new version? we update legendary, maybe that fixes this

**Comment by ximian** [comment]
Updating Heroic to the latest version has resolved the issue for me.

**Comment by zShxck720** [comment]
> Can anyone try with the new version? we update legendary, maybe that fixes this

Seems fine and it stays logged in after reboot. Great Thanks to you all
