### ISSUE TITLE
Allow customizing launch command

### ISSUE THREAD

**Issue by sPOiDar** [Heroic-Games-Launcher/HeroicGamesLauncher#271]
When launching a game it is sometimes necessary or desirable to prefix the launch command with a wrapper, for example `prime-run` for hybrid graphics.

Currently there is an option to append launch arguments (under `Other` -> `Game Arguments`), this might be modified to allow a templated command, the way that Steam does it, whereby including a `%command%` string in the field causes the field to instead substitue the original commandline for that variable, allowing for the following variations:

- `-nolauncher` - appends the `-nolauncher` flag to the game command
- `prime-run %command% -nolauncher` - prefixes the game command with `prime-run` and appends the `-nolauncher` flag

The `%command%` string is replaced by the full command-line that would otherwise be used, including any wine/proton/gamemode/whatever prefixes that are toggled by options.,

**Comment by adityaruplaha** [comment]
Should be trivial to implement. If any new developers wanna start contributing to Heroic, this is a great opportunity.

However I'm not willing to touch this right now since that section of the code is undergoing major refactors. Maybe in 1.6.

**Comment by flavioislima** [comment]
There is no need to implement this since it is already implemented. Everything that you will putt on the environment variables, will go before the launch command, just like ok steam. And everything on launcher arguments will go after the command.

In your case, you just need to make sure that the prime command goes last on the environment variables.

👍

**Comment by flavioislima** [comment]
What we could discuss is maybe renaming the environment variables to anothet thing. But it works the same as on steam, before the command.

**Comment by sPOiDar** [comment]
Wait, you're saying that the environment variables field is not parsed and added to the env, but is instead just verbatim prepended to the command line via a shell or something? I don't know that dual-purposing that field is good design, and the Steam method is likely familiar to most of your users already..

**Comment by flavioislima** [comment]
Yeah, heroic is a gui so it doesn't launch the games itself. It calls legendary with the environment variables on a shell command. You can see the launch command when running heroic from the terminal.

So, when I designed this field it was to be used to pass environment variables, but since it is just commands to run before the launch command it will work with anything.

Like on the first versions, it didn't have game mode option, but it worked when passing gamemode there.

We will add a prime option in the future, but i don't know exactly how this works since I use a desktop.

Some people uses prime run, other pass some variables. So I'll need to investigate one way that will work for everyone.

What's your suggestion?

**Comment by sPOiDar** [comment]
So what's the resolution to this issue? I don't think there's a one-size-fits-all prime solution, since the mechanism depends on user choice and hardware, and command prefixing is just generally useful (tinker/mangohud/etc are other examples). In the current state, it's unreasonable to expect users to work out that they should jam these into an env field.

**Comment by adityaruplaha** [comment]
Just put the prefix in the env field. We're thinking about this in internal discussion cuz the UI will be reworked.
