### ISSUE TITLE
Opening a game on steam no steam overlay

### ISSUE THREAD

**Issue by szentigrad3** [Heroic-Games-Launcher/HeroicGamesLauncher#2835]
### Describe the bug

when i launch a game through steam.. the steam overlay doesn't work or say i'm in that game

### Add logs

```text
check below
```

### Steps to reproduce

1. Just launch the game through steam

### Expected behavior

launch the game through steam able to use the steam overlay

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Windows 11"]:

### Additional information

[heroic-2023-06-28T07_36_40.999Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/11929199/heroic-2023-06-28T07_36_40.999Z.log)

**Comment by thatpandae** [comment]
Same

**Comment by Nocccer** [comment]
For me that Sounds more like a problem in steam side not heroic. Heroic can't handle the steam overlay. I think that steam overlay is not supported for every non steam game. Maybe check the internet if there is a solution. Maybe has something todo with wine versions.

**Comment by TimoAcker** [comment]
I had the same problem. It's not a bug, but you could say it's a "missing heroic documentation".

Solution:
First, You need to add heroic games launcher as a non-steam game.
Then you need to open the properties of heroic games launcher in steam and add "--no-sandbox" to the launch parameters.
Now the steam overlay of every non-steam game (that is added to steam by heroic) works fine!

This is a definitively true for SteamOS, but I'm not a 100% sure for Windows.

BTW, without "--no-sandbox" you also have the problem, that the controller settings of any non-steam game (added by heroic) is ignored, and the heroic controller settings (or desktop controller settings?) are used.

**Comment by MrRulf** [comment]
#It's not a bug, but you could say it's a "missing heroic documentation"
@Handfratze 

I wouldn't say so, since what you describe seems more like a workaround than intended, or whats going wrong with launching trough steam in the first place. 
I'm on Archlinux and having the same issue as others, something unmentioned yet tough: For me steam doesn't recognize the game as running, after i started it trough steam, it's running only for a very short period and then steam doesn't see it anymore. 

#For me that Sounds more like a problem in steam side not heroic. Heroic can't handle the steam overlay. I think that steam overlay is not supported for every non steam game.
@Nocccer 

I don't think it's a steam problem (at least in my case im not there (yet)) because steam doesn't see the game as running after it started. Of course it can't provide the overlay or say your in a certain game when it can't even see the game running. It seems like steam loses track somewhere on the way of launching the game. 

Another thing I noticed is that the heroic launcher minimizes (or restarts even) when I start the game trough steam, not tough when I start it trough heroic. My guess is that steam somehow checks if heroic is running, to launch it, if it's not, however therefor sees it's task as done when the check is complete. Considering what steam runs probably looks something like this: 
`if heroic.running == false
  launch heroic;
launch game`

it is done when the game starts and doesn't follow trough on the game. 
This kinda makes sense, when an ubisoft or ea game is launched trough steam the corresponding launcher is also started (uplay/origin) and when the game is closed later those launchers keep running in the background, without steam still showing the game as running. It's not random, entirely new or impossible to explain. 

For launchers you absolutely want this, if one is already running u don't want to open it again or steam to close it just because u closed the game u launched trough steam. Not closing a launcher if opened trough steam might be a bug, a feature or just their decided handling for the special case, not relevant here tough. 

So like I said, I think the game is handled similar to a launcher, or the check or whatever runs with the launch trough heroic, is seen as the game. For me here's where my idea ends tough, can somebody confirm or deny my guesswork? Or maybe, with a deeper understanding of heroic, maybe even tell where to go on with this?

**Comment by KomakiTigerDrip** [comment]
If anyone runs into this in the future, solution is found here: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4415#issuecomment-2725068448

> you should close heroic before running a heroic game from steam
