### ISSUE TITLE
Installation heroic 2.10.0 rpm blocked

### ISSUE THREAD

**Issue by scroll44** [Heroic-Games-Launcher/HeroicGamesLauncher#3203]
### Describe the bug

 Hello,

Until now I installed heroic game launcher rpm without any problem. The latest "heroic-2.10.0.x86_64.rpm" blocks

Distribution Mageia 9

with urpmi :

[root@localhost Downloads]# urpmi heroic-2.10.0.x86_64.rpm
The requested package cannot be installed:
heroic-2.10.0-1.x86_64 (because gtk3 is not satisfied)
Do you still want to continue? (Y/n) n
[root@localhost Downloads]# urpmi -p gtk3
No package named gtk3

With Software Installer: requires libuuid, gtk3, libXtst

Solution :

First remove the old :

urpme heroic-2.9.2-1.x86_64

There's nothing to say :)

Then force rpm, but we're not going to let ourselves be em....ed by a simple program, are we?

rpm -i --nodeps heroic-2.10.0.x86_64.rpm

Well, that's that. Heroic launches in version 2.10 impeccably

May you do the necessary to not have any problem since before ?

Thanks

### Add logs

```text
...
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

...

### Heroic Version

Latest Stable

### System Information

Mageia 9

**Comment by flavioislima** [comment]
i am not sure what do to in this case. Our package cannot ask to remove any other package, even it's own, from the system since it does not even know it exists or not.

So the only thing we can do is to tell people to remove the old first if it does not work.

Also, RPM might be discontinued in the future since our plans is to push Flatpak more since it is the more stable, easier to debug and to reproduce. Because the flatpak install is the same no matter the distro so it is better for everyone. :)
