### ISSUE TITLE
Is it possible to only use the .wine prefix already on the system and not seperate prefixes?

### ISSUE THREAD

**Issue by DeeDeeRanged** [Heroic-Games-Launcher/HeroicGamesLauncher#3233]
### Describe the bug

Probably it has been asked before so pls forgive me.

Is it possible for Heroic to install the games all in the same prefix like ~/.wine and not like in seperate prefixes in the heroic ~/Heroic/Prefixes//default/<whatevergame> as it would save abt. 1.7 to 2 GB per gameand doesn't get riddled with different dxvk's and what not.
I find this a waste of space, specially if you are using a notebook with a lot of games.

Only using Herioc as a replacement for the Epic Games Launcher and I have always installed games in the same .wine prefix.

### Add logs

```text
no logs
```

### Steps to reproduce

Nothing else to ask

### Expected behavior

Possibility to install games in the same profix.

### Heroic Version

Latest Stable

### System Information

- Debian testing/trixie

**Comment by CommandMC** [comment]
This is already possible, you can choose a different prefix directory in the install dialog

Using the same prefix for everything is however not recommended, since different games may require different steps to get working, which might in turn break other games. There's a reason Steam, Lutris, Heroic, and (in part) Bottles do it this way.
