### ISSUE TITLE
WinGet should install legendary as a dependency

### ISSUE THREAD

**Issue by Linx-ESP** [Heroic-Games-Launcher/HeroicGamesLauncher#3463]
### Problem description

Since legendary has to be installed, should be better to use the feature of a package manager and not install them each tiem for each program. WinGet allows for dependencies, and legendary is distributed via winget too.

This would also make legendary update independently of Heroic, not needing a new heroic version in case of a legendary update.

### Feature description

As written in https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23163%20-%20Dependencies.md and https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json#L215 the winget manifest should be updated to install legendary as a package AND not include it in the heroic installer

**Comment by flavioislima** [comment]
We are not the winget maintainers so we have no way to change that.

Also, heroic already comes with legendary. We could update it automatically from heroic but we like to test before upgrading because some things could break on heroic after a legendary update.

**Comment by Linx-ESP** [comment]
In the other hand,
This would be a welcome change so other programs don't have to install each time (playnite for example), and default install of legendary installs to $PATH (IIRC), so install path wouldn't be an issue.

And legendary being relatively small might be easier to keep an eye for breaking changes via github PRs

**Comment by CommandMC** [comment]
Heroic needs to have its own version of Legendary
- We are just using the latest release *most of the time*, but occasionally we're not (instead using a version with specific features or fixes that aren't upstream yet)
- Heroic is designed with a specific version of Legendary in mind. If we would just use a system-installed version and that system-installed version works differently somehow, Heroic will not work properly

Installing Heroic's version of Legendary system-wide isn't a good idea either, since you generally *want* the freedom of installing new Legendary updates as soon as they're out
