### ISSUE TITLE
Support EA Origin as Source

### ISSUE THREAD

**Issue by yoshimo** [Heroic-Games-Launcher/HeroicGamesLauncher#352]
Is your feature request related to a problem? Please describe.
Having multiple launchers fighting for download bandwith and systray space isn't the best user experience
Same is true for the social features

Describe the solution you'd like
Heroic being able to download/install&update from EA Origin, read game news and talk to friends as well as buy games/dlcs/services. Be Notified about deals for your wishlist and free games. Sync Savegames over the cloud.

Describe alternatives you've considered
GoG Galaxy launcher.

**Comment by Flonky** [comment]
The problem here is that GOG talks to the origin launcher and doesn't start it itself. That wouldn't work with heroic because there is no origin for linux. We would need an project like legendary, just for Origin and not epic.
If you find something like that we could look at how to integrate that^^
Btw an GOG integration is in the works

**Comment by yoshimo** [comment]
If you say what is needed to do any of it, me and my fiddler will go hunting.

**Comment by adityaruplaha** [comment]
There's no public facing EA Origin API, so this will probably not happen. An entire API will have to be reverse engineered, and they can break stuff anytime.

**Comment by flavioislima** [comment]
Same as I answered for the Blizzard issue. #347
