### ISSUE TITLE
Install Directx9 by default for games

### ISSUE THREAD

**Issue by Rathmox** [Heroic-Games-Launcher/HeroicGamesLauncher#3545]
### Problem description

I wanted to play Return to Castle Wolfenstein from GOG. But when using Wine-GE, the game did not show anything, but on proton it did.
Installing the game through Lutris works though (it only shows a window but the issue is not related to Heroic).
It turns out I had to install directx9 myself with winetricks to make the game work on Heroic.

### Feature description

Install DirectX9 on all prefixes because a lot of games requiere it.

**Comment by imLinguin** [comment]
Starting version 2.13 (probably releases tomorrow), Heroic will download required redistributables like GOG Galaxy

**Comment by arielj** [comment]
Also, we don't install winetricks packages by default on purpose because things could break too (unless the game specifies that as imLinguin mentions it will be done in the future release).

To install known fixes we have the https://github.com/Heroic-Games-Launcher/known-fixes repo so we add things we know will fix specific games.

**Comment by Rathmox** [comment]
Ok good, I will go that
