### ISSUE TITLE
Installing FlatOut from Gog fails

### ISSUE THREAD

**Issue by StagnationPoint** [Heroic-Games-Launcher/HeroicGamesLauncher#3577]
### Describe the bug

Installing FlatOut from Gog fails because /dev/fd0 does not exist.

/home/hmm/Games/Heroic/FlatOut/prefix/dosdevices/a:: is a symlink to /dev/fd0, and /dev/fd0 does not exist on this machine, which generates an ENOENT error.

I'm not sure why a prefix is involved, since I selected the Linux version to install.

### Add logs

```text
(15:25:09) ERROR:   [DownloadManager]:  Installation of 1207658693 failed with: Error: ENOENT: no such file or directory, stat '/home/hmm/Games/Heroic/FlatOut/prefix/dosdevices/a::'
```

### Steps to reproduce

Install FlatOut from Gog (it's currently free), select the Linux version.

### Expected behavior

Installation should work.

### Heroic Version

Latest Stable (Flatpak)

### System Information

Kubuntu 23.04, running the Flatpak via Flathub.

**Comment by arielj** [comment]
This was fixed by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3570

You can use the flatpak from the build here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/7907959857

or just install the Windows version (the linux native version is the windows version with a wine and a prefix included, so it's basically doing what Heroic does already, and you will save like 600mb)

**Comment by StagnationPoint** [comment]
I searched a bit before filing the ticket but apparently not hard enough. Thanks!
