### ISSUE TITLE
Offer an option to directly upload logs

### ISSUE THREAD

**Issue by CommandMC** [Heroic-Games-Launcher/HeroicGamesLauncher#3863]
### Problem description

Sending logs into Discord can be a pain point of support requests. Between getting the file from a Steam Deck, Flatpak Discord's permission problems, and general confusion, it can be hard to get the (full) log.

### Feature description

Display a button to directly upload the log file to a pastebin service and display/copy the URL. I've borrowed this idea from the EndeavourOS helper `eos-sendlog`, which uses [these](<https://github.com/endeavouros-team/eos-bash-shared/blob/15d7f9e7ce9a7812099491484ae31dc1e06c2072/eos-sendlog-helper#L51-L55>) pastebin services

**Comment by arielj** [comment]
I wonder how compatible is that with things like GDPR. I think it's fine but I'm not sure if that applies to something like heroic and using a third-party service to upload them.

the main concern is that I think that if we provide an upload file mechanism inside heroic we might need to provide a mechanism to also remove those uploaded files on demand since they include the user name and some logs might show more information that maybe identifies a user?

Currently users have to do it manually so it's on them to pick the service and clean the file if they want to, but not sure how that works if heroic does that for them.
