### ISSUE TITLE
In the Add Game dialog, show a message telling users about the Import Game option

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#3902]
### Problem description

It happens really often that users want to add an Epic game they already installed on windows (for example) on their linux system, and they incorrectly use the `Add Game` (sideload) feature instead of importing the game, so they end up with a broken game because it's not going through the correct DRM of the store.

### Feature description

In the Add Game dialog, show a message to let users know that, if they want to add a game from GOG/Epic/Amazon, they should actually log in, click the install button, and then the Import Game button instead.

### Alternatives

I don't know, anything that prevents broken Add Game games works for me.

**Comment by R1kaB3rN** [comment]
Agreed and this should impact users who have umu enabled as the runtime, as they would miss out in potential game fixes. Looking at the code, if I understand correctly, the application of protonfixes are dependent on the appropriate `UMU_ID` being set and I'm assuming this only happens if they do the steps you had described. Otherwise, Heroic doesn't try to set it for a side loaded game.
