### ISSUE TITLE
Per-Game Wine prefixes like Lutris

### ISSUE THREAD

**Issue by 20PercentRendered** [Heroic-Games-Launcher/HeroicGamesLauncher#394]
**Is your feature request related to a problem? Please describe.**
Having multiple games installed will conflict, because they are all in the same .wine directory.

**Describe the solution you'd like**
Each game should have their own wineprefix, like in Lutris

**Comment by flavioislima** [comment]
Hi. Heroic already works like this.
Just go to the game settings and select or create a new prefix.

**Comment by 20PercentRendered** [comment]
But the default is ~/.wine, and it should be ~/Games/[game-name]

**Comment by flavioislima** [comment]
> But the default is ~/.wine, and it should be ~/Games/[game-name]

No. This is not how it supposed to be. 
You might want to do it and you can have one prefix for every game, but most of the time, your games will work under the same prefix. From time to time you need to test something or install some specific thing that might he good have a separate one, or if you want to use different versions of wine. But not for every game.

My personal recommendation is to have a prefix for wine, another for steam proton and another for proton custom. I use it like this for quite sometime and I seldom have any issues playing my games.
And you will save space on your drive as well since tiu will have shared libraries and configurations. 

Heroic starts the configuration with the default that wine uses when you call it directly that is .wine.

But like I said, you can go to the game settings and create a folder for every game if you prefer like that.
