### ISSUE TITLE
Filter by genre / tags in the library

### ISSUE THREAD

**Issue by TuTiuTe** [Heroic-Games-Launcher/HeroicGamesLauncher#3957]
### Problem description

sometimes I just want to quickly browse through my games looking for a specific tag (most of the time multiplayer, to try out with friends all the free multiplayer games I got on epic games) but I have to manually look them up

### Feature description

most of the games, when selecting them in the library fetch their genre / tags data (for instance DOOM 64 is labeled Action and Shooter), thus the launcher could fetch all these tags, add them to a list, and in the filters list quickly browse through the games by genre

### Alternatives

I think that would be the easiest and fastest approach, but an alternative would be steam's dynamic collection which would be more of a hassle to implement

**Comment by arielj** [comment]
We can't really implement something like that unless we find a good source were we can fetch all this information in bulks.

We currently do that only when opening the details page of a game because we can only fetch one game at a time from a source we don't control.

Fetching all games at startup to create that index will have a couple of problems: we'll end up generating hundreds of requests to fetch that information, which means a lot of load to whatever service we use and a lot of connections opened (most likely reaching rate limiting or connections limits), and the experience will fill broken.

Also, the information we get is not always accurate cause we do a word match of the titles and not really fetch exact games, so you may end up with a game with a completely unrelated set of categories.

So, if at some point, that service exists and we can use it and it's optimized for this purpose, this feature could be implemented. Until that happens it's just going to eat a lot of resources and possibly create problems for a third party site.

Finally, a similar feature request is here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1441 so I'll close this issue and any conversation can happen on that other one that includes this and other filters ideas
