### ISSUE TITLE
Issue when downloading multiple games in parallel

### ISSUE THREAD

**Issue by djibux** [Heroic-Games-Launcher/HeroicGamesLauncher#403]
I am experiencing the following issue with version 1.7.0.
Let’s say I want to install two games.  Game A, that is pretty big, and Game B that is much smaller.
  * I first start to download Game A
  * I then start to download Game B
  * Game B becomes ready
  * Then Game A becomes ready and Game B is no longer available: it is still on disk, but no longer appears in the interface.

**Comment by djibux** [comment]
I should mention that importing the game works after that.  There is no need to re-download it.

**Comment by flavioislima** [comment]
Would be good to run heroic from the terminal and check the output.
Also, which games? Which distro?

The issue template is there to be used not erased.
We need those information to start investigating.

**Comment by djibux** [comment]
Mmmh, I'm sorry about the template.  I'm not sure how but I managed to get to an empty issue.

**Describe the bug**
When downloading multiple games, some games are downloaded but are not marked as "ready" in Heroic.

**To Reproduce**
Steps to reproduce the behavior:

1. Open Heroic
2. Start downloading any game (Game A)
3. Start downloading any other (Game B), preferably smaller than game A, so that it is downloaded faster than Game A.  It should become "ready" while Game A is still downloading
4. When Game A is fully downloaded and becomes "ready", Game B is no longer "ready" in the library.  (Files are still on disk an the game can be imported manually). 

**Expected behavior**
Both games should be ready to run.  Game B shouldn't be dismissed/forgotten.

**Screenshots**
Not sure it helps…

**Desktop (please complete the following information):**

- OS: Debian
- Version: Bullseye
- Game: Any
- Wine/Proton version: Any (Wine 5.0.3, Proton experimental, Lutris 6.4)
- Hardware specs (RAM, CPU, GPU): 8Gb, Intel(R) Core(TM) i7 @ 3.33GHz, AMD Vega 56

**Additional context**
See [install.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/6591055/install.log) with 20XX and Axiom Verge being downloaded in parallel.

**Comment by flavioislima** [comment]
Ok, I was able to reproduce it. 
Also, this is a bug in Legendary. For some reason, if you put two games to install on legendary and run `legendary list-installed` right after installing, that's how Heroic does to update the game information, it erases from the list the first installed game.
That's a really weird bug.

But I won't bother guys from legendary since this kind of behavior is not expected. So we will need to change something on our side.

Thanks for reporting!

**Comment by djibux** [comment]
I wasn't expecting that issue to be in Legendary itself!  I had a look at the Library class in your code but couldn't find any obvious issue :)

I will report it upstream because I believe downloading games in parallel is a frequent use case.

**Comment by flavioislima** [comment]
> I wasn't expecting that issue to be in Legendary itself!  I had a look at the Library class in your code but couldn't find any obvious issue :)
> 
> I will report it upstream because I believe downloading games in parallel is a frequent use case.

I tested and also confirmed on the legendary discord that is not possible to have parallel downloads on it. I just dont know how it took so long to someone find this bug. I never found as well.

The only fix I can think now is to implement a downloads queue on heroic. Like it's on Steam. Instead of parallel downloads.

**Comment by adityaruplaha** [comment]
I'll check if the issue is trivial. It probably isn't, in which case major refactors will be required to Legendary's codebase, something I'm not really ready to undertake. But I'll have a look if I can fix the issue upstream.

**Comment by flavioislima** [comment]
> I'll check if the issue is trivial. It probably isn't, in which case major refactors will be required to Legendary's codebase, something I'm not really ready to undertake. But I'll have a look if I can fix the issue upstream.

They will fix it on 1.0. Since then they will stop using json files. Right now the latest game downloaded will overwrite the installed.json file so that's why only the latest one show as installed.

I tested multiple times with legendary only.

Our solutions is to have a queue now, this will need us to change several things in heroic.

But still, in more than 5 months this is the first time someone mention this so I do not consider it to be a critical bug. But needs to be fixed eventually. 👍

**Comment by djibux** [comment]
OK if Legendary is already aware of the issue maybe there is no point in reporting it.  And you're right, from the terminal I never felt the need to download multiple games at once.

**Comment by flavioislima** [comment]
Partially fixed for now on #529 .
But a proper fix will be when we have a queue for the downloads and updates. this is being developed.
