### ISSUE TITLE
Wine-GE no longer campatible with Gamescope on Steam Deck

### ISSUE THREAD

**Issue by Emurikku** [Heroic-Games-Launcher/HeroicGamesLauncher#4114]
### Describe the bug

Hello,

Since the latest versions of SteamOS (3.6), games using Wine-GE won’t recognize your controller anymore. Steam Input will stay stuck on keyboard mode.

This was bound to happen, as Wine-GE is now kinda old, but I think the future versions of Heroic should now recommend Proton-GE by default.

You’ll have to transfer your save files as the prefixes are not the same: from “drive_c/users/deck/…” to “pfx/drive_c/users/steamuser/…”. 

### Add logs

```text
.
```

### Steps to reproduce

1. Launch a game with Wine-GE;
2. Go to Gaming Mode;
3. No controller input, but keyboard will work.

### Expected behavior

Controller inputs should work.

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: SteamOS

**Comment by m3e-g** [comment]
Does it work with Proton then?
I think it's the same issue as #4108 and something broke when flatpak platform was updated to 24.08

**Comment by Emurikku** [comment]
Yes, it’s related indeed. Maybe the issue will be solved with a new refresh of the Flatpak.

But I can confirm that it works with Proton-GE. Anyway, with UMU, it seems that Wine-GE is soon to be deprecated.

**Comment by arielj** [comment]
the flatpak change was reverted, a new update to heroic flatpak should appear soon

**Comment by Emurikku** [comment]
Yes, it did.

Wine-GE works again with this release, but should we still use it? It’s been a long time since the latest release, and GE seems focused on UMU now.

**Comment by arielj** [comment]
> Yes, it did.
> 
> Wine-GE works again with this refresh, but should we still use it? It’s been a while since the latest release, and GE seems focused on UMU now.

should/shouldn't is hard to say, it's an option, it's outdated but still works, so I think it's fine to keep it as an option

at the end of the day, you can use whatever makes a game work, and it can be different for different games

**Comment by arielj** [comment]
the issue seems to have been something with flatpak, it could have happened with proton-ge too for all I know

nobody can predict what's going to create issues, maybe nothing breaks wine-ge anymore or something breaks proton-ge, nobody knows

I know the ideal for the future is to not use wine-ge anymore and use proton-ge + UMU, but there are still issues with that combination too in heroic (like currently winetricks doesn't work in that case, so that breaks other games)

**Comment by Twig6943** [comment]
pretty sure the winetricks issue will be fixed in the future (also does it also not work when you manually run via WINEPREFIX=placeholder winetricks )

**Comment by casasfernando** [comment]
I think this issue should be closed to avoid confusion.
The cause of the problem was unrelated to Wine-GE. It was a Flatpak issue.
I could confirm this because I use HGL in Flatpak and AppImage release flavors and only Flatpak was affected.
Moreover Steam Input issue only affected Gamepad emulation layouts, while kbd+mouse continue to work as usual.

Wine-GE is very solid in my experience and much better to troubleshoot issues with non-Steam games than Proton-GE. It’s a pity that is not maintained anymore.
I’m currently using it with all of my non-Steam games and will certainly continue to do so.

Just my two cents.
