### ISSUE TITLE
Games don't launch

### ISSUE THREAD

**Issue by TurboWafflz** [Heroic-Games-Launcher/HeroicGamesLauncher#425]
**Describe the bug**
When attempting to launch a game it changes to saying playing but the game does not launch and I get the following error in the terminal:
```
Error occurred in handler for 'launch': TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (fs.js:1436:5)
    at go$writeFile (/opt/heroic/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:139:14)
    at Object.writeFile (/opt/heroic/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:136:12)
    at /opt/heroic/resources/app.asar/build/main.js:365:23
    at Generator.next (<anonymous>)
    at /opt/heroic/resources/app.asar/build/main.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/heroic/resources/app.asar/build/main.js:23:12)
    at /opt/heroic/resources/app.asar/build/main.js:364:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**To Reproduce**
1. Install game
2. Click Launch

**Expected behavior**
The game should launch as it does when running Legendary directly

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: 20.04
- Game: Tested MudRunner, Among Us, and Tales of the Neon Sea
- Wine/Proton version: 5.0
- Hardware specs (RAM, CPU, GPU): 24GB RAM, 2x Intel Xeon E5620, Radeon RX 570

**Comment by flavioislima** [comment]
You generated the install package from git? Because we had this bug but not on any release.
It was fixed so maybe generate the package again.

**Comment by TurboWafflz** [comment]
Nope, I just downloaded the deb from the 1.7.0 release.

**Comment by flavioislima** [comment]
> Nope, I just downloaded the deb from the 1.7.0 release.

Really? No one else had this bug and 1.7 is out for more than 2 weeks.
Try version 1.8 then.

**Comment by TurboWafflz** [comment]
It's the same on 1.8. I also tested running it on my laptop (also running Ubuntu 20.04) and got the same error.

**Comment by flavioislima** [comment]
Yeah, I rebooted now to test on pop 20.10 and it worked as expected.

Well, some error is happening when you are trying to launch the game, that error that you saw is happening because heroic is not being able to check the error, but some other error is happening.

I think might be some permission issue. Check if your user can read and write the game folder. Check if you have python version 3.8 or higher as well.

@adityaruplaha that is the same error you fixed yesterday right? It seems older than yiur last refactor then.

**Comment by adityaruplaha** [comment]
> Yeah, I rebooted now to test on pop 20.10 and it worked as expected.
> 
> Well, some error is happening when you are trying to launch the game, that error that you saw is happening because heroic is not being able to check the error, but some other error is happening.
> 
> I think might be some permission issue. Check if your user can read and write the game folder. Check if you have python version 3.8 or higher as well.
> 
> @adityaruplaha that is the same error you fixed yesterday right? It seems older than yiur last refactor then. 

It was, the catch block was broken. It was never getting triggered though, so we didn't notice. Should be fixed now.

**Comment by TurboWafflz** [comment]
I have Python 3.8.5 and it's definitely not a permission issue as my user created the folder and also downloading games works fine. It doesn't happen on a fresh 20.04 VM though, so I'm guessing it's just some issue that happens to be present on both my desktop and laptop instead of an actual bug in Heroic. Is there any way to make Heroic be more verbose so I could figure out what's causing the issue?

**Comment by flavioislima** [comment]
> I have Python 3.8.5 and it's definitely not a permission issue as my user created the folder and also downloading games works fine. It doesn't happen on a fresh 20.04 VM though, so I'm guessing it's just some issue that happens to be present on both my desktop and laptop instead of an actual bug in Heroic. Is there any way to make Heroic be more verbose so I could figure out what's causing the issue? 

Makes sense.
Yeah, we are working on this right now and next version will store logs for everything so it will be easier to debug.

**Comment by xenon205** [comment]
Hi, i have the same problem with launching games. I'd like to try version 1.8 but becouse of me beeing a noob i can't compile this code using yarn.
"yarn dist deb
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dist'"

What am i doing wrong here ? :|

**Comment by flavioislima** [comment]
> Hi, i have the same problem with launching games. I'd like to try version 1.8 but becouse of me beeing a noob i can't compile this code using yarn.
> "yarn dist deb
> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dist'"
> 
> What am i doing wrong here ? :|

You don't need to compile 1.8, it's on the release page. Just download and use it.
Just for you to know, there are some bugs that we are fixing since 1.8 is not stable, it's a testing version.

**Comment by flavioislima** [comment]
And I think you have installed the wrong yarn package.

**Comment by Nocccer** [comment]
@xenon205 
Year sudo apt install yarn is not working like that. Installs some other pacakage.
See Alternatives section to install the real yarn .deb pacakge.
https://classic.yarnpkg.com/en/docs/install#debian-stable

**Comment by xenon205** [comment]
Thanks for all the responses . After installing 1.8 version and picking Proton Experimental there was a message that it will not work with proton. Idk if this message was in 1.7 but after changing wine to "normal" everything was working fine. 
Because my harware works better with proton i will use Lutris for now. Maybe in future i will check this app again.

**Comment by flavioislima** [comment]
> Thanks for all the responses . After installing 1.8 version and picking Proton Experimental there was a message that it will not work with proton. Idk if this message was in 1.7 but after changing wine to "normal" everything was working fine. 
> Because my harware works better with proton i will use Lutris for now. Maybe in future i will check this app again.
> 

You can try using proton but don't ask for help if it doesn't work because proton is not supported outside of steam.

We added the message because of that and because we get several support issues regarding it but nothing stops you of trying. Lutris also doesn't support proton, and you can't even add it.

**Comment by xenon205** [comment]
> > Thanks for all the responses . After installing 1.8 version and picking Proton Experimental there was a message that it will not work with proton. Idk if this message was in 1.7 but after changing wine to "normal" everything was working fine.
> > Because my harware works better with proton i will use Lutris for now. Maybe in future i will check this app again.
> 
> You can try using proton but don't ask for help if it doesn't work because proton is not supported outside of steam.
> 
> We added the message because of that and because we get several support issues regarding it but nothing stops you of trying. Lutris also doesn't support proton, and you can't even add it.


It's easy to add proton to lutris. All you need to do is make a shortcat of proton(in my case i use experimental) in a ~/.local/share/lutris/runners/wine/ 

Give it a try and you will be able to pick it in lutris

**Comment by flavioislima** [comment]
@xenon205 yeah,i know that. But that's not proton, you're using wine only. To use proton you need to use the proton wrapper, the proton binary inside the proton folder. That's the one that wrapps the libraries to increase the compatibility.

Heroic gets the right proton and the wrapper, but still it might not work because proton was made for steam, that's why we added the message.

Personally I use proton on Garuda that is a game focusing distro and is bloated with all kinds of libraries and helpers.

I also have pop and on pop proton outside of steam complains about missing libraries. 

If you want to use the wine binary of the proton folder, you can add it as custom wine on heroic, it will work the same as works in lutris.

But like I said, you can also use proton on heroic, it will find all your steam proton and will use the wrapper, but the final result will depend on other variables.

**Comment by xenon205** [comment]
Well... it's great to be a frog in the well :D i will have to look in to this more...

**Comment by xenon205** [comment]
I gave it one more try and it works... weird. 
On lutris wine 6.3 few games work, but on Wine 6.10, or Proton Wine non  that i tried. 
i'm on 1.8 rc1

**Comment by flavioislima** [comment]
@TurboWafflz I'll close the issue since this doesn't looks like an heroic problem. But feel free to reach us on discord if you need further help.
