### ISSUE TITLE
Cant update my games

### ISSUE THREAD

**Issue by leath-dub** [Heroic-Games-Launcher/HeroicGamesLauncher#544]
Any time i try to update the game through the heroic launcher it just stops and cancels it. Im not sure if this is the right place to ask questions like this.

**Comment by flavioislima** [comment]
Please reopen the issue using the template. It exists for a reason. Thanks.

**Comment by leath-dub** [comment]
where is the template?

**Comment by flavioislima** [comment]
When you click on New Issue >  Bug. Thats the template. Just fill the info there 👍🏽

**Comment by flavioislima** [comment]
But before opening a new issue, normally this might be because you have no space left on the device. Check if that's the issue. I just updated a game here without issues.
You need to have at least the game size available to update.
So if the game is GTAV, it will need more than 100GB free to update.

**Comment by leath-dub** [comment]
ic ill check that now, Is there somewhere to see how much space is needed for the update. The issue is probably my pc because i get the cancel notification from popos pop up

**Comment by flavioislima** [comment]
Go to our discord then, its better to get help than here:
https://discord.gg/rHJ2uqdquK
