### ISSUE TITLE
Support Proton outside the default Steamfolder in Home

### ISSUE THREAD

**Issue by JakobDev** [Heroic-Games-Launcher/HeroicGamesLauncher#592]
I noticed that Heroic only finds Proton if it's installed in the default steam folder at ~/.steam/steam/steamapps/common/ and not on any other folder. Would be nice if you support other directories. Steam saves all directories in the file ~//home/jakob/.steam/steam/steamapps/common/.

**Comment by flavioislima** [comment]
Which file? this is a folder. I could not find any way to get proton installed on other partitions that's why heroic could not find them.

**Comment by JakobDev** [comment]
Sorry. had the wrong path in my clipboard. The right path is ~/.local/share/Steam/steamapps/libraryfolders.vdf. I had selected the folder on my other partion as my default folder, so Steam had installed Proton there. I had to move Proton to my System drive to be found by Heroic.

**Comment by flavioislima** [comment]
Ok, I'll try to find a way to get those folders.
Thanks for the info.

**Comment by Krafting** [comment]
Hey there! I just runned into this exact issue, I installed a proton version on steam and steam installed it in another Library, I spent half an hour trying stuff to make it show up on Heroic until I found this, I moved the Proton to the default steam installation folder and it is now detected.

I hope this will be fixed in the future, either by checking the `libraryfolders.vdf` or adding a setting to specify where are others Proton versions. Or at least be more documented in the app itself when selecting Wine versions.

**Comment by flavioislima** [comment]
> Hey there! I just runned into this exact issue, I installed a proton version on steam and steam installed it in another Library, I spent half an hour trying stuff to make it show up on Heroic until I found this, I moved the Proton to the default steam installation folder and it is now detected.
> 
> I hope this will be fixed in the future, either by checking the `libraryfolders.vdf` or adding a setting to specify where are others Proton versions. Or at least be more documented in the app itself when selecting Wine versions.

You can add proton from anywhere using the Add custom wine proton setting. Just make sure you select the proton binary for proton and wine binary for wine.

Reading from other libraries is possible but it's a lot of effort since steam uses their own file type (vdf) to store the info and it's not like a json that is easier to read. We will need to convert it and treat it. But it's planned.

**Comment by JakobDev** [comment]
@flavioislima  [Take a look at this](https://pypi.org/project/vdf2json/)

**Comment by flavioislima** [comment]
> @flavioislima [Take a look at this](https://pypi.org/project/vdf2json/)

This one would be more python to deal with inside heroic.
There is a npm package that does the same. We will implement it when we have the time.

**Comment by flavioislima** [comment]
implemented on #1369
