### ISSUE TITLE
Red Dead Redemption 2 (epic version) wrong locale. May affect other Rockstar games.

### ISSUE THREAD

**Issue by Adiker** [Heroic-Games-Launcher/HeroicGamesLauncher#805]
**Describe the bug**
Rockstar Games Launcher (Launcher.exe) opens with commandline argument "-epiclocale=en", which essentialy forces the game language to English. I have the launcher installed in my own language (Polish) so this argument is for some strange reason added by Heroic. When I run the game with "-epiclocale=pl", it normally works in Polish language (also the Social Club is affected by this). I compared the original Epic Games Launcher and it does not have this issue.

**Add Logs**
Nothing interesting I think, but here they are: 
[logs.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/7755717/logs.txt)

**To Reproduce**

1. Run RDR2 (Epic Store version) on Heroic Launcher. Possibly it affects other rockstar games too.
2. The game will be in English because Rockstar Launcher launches with "-epiclocale=en" argument.

**Expected behavior**
Epiclocale should be tied to Rockstar Games Launcher language.

**Screenshots**
I don't think they're necessary, but if the issue is not reproducible I can provide them.

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Heroic Version: 1.11.0-beta.2 (happens on stable too)
- Game: RDR2 and possibly other Rockstar games on Epic.
- Wine/Proton version: 6.23-staging
- Hardware specs (RAM, CPU, GPU): Ryzen 5 2600, RX 5700 XT (Mesa), 2x8GB RAM

**Additional context**
The locale may be tied to system language or Epic region (because I have both in English) but anyway, on original Epic Launcher it detects the Rockstar launcher language and launches it with the correct language. I'm curious to know what the issue is and if it's possible to fix it.

**Comment by flavioislima** [comment]
Hi!
When I started Heroic I wanted to add language support for the games and then pass the user locale to it. The thing is that Epic doesn't have a standard for that and this works for some games and for others doesn't.
The weirdest case is RocketLeague that is an Epic game that doesn't respect the locale.
for it to work you need to pass a parameter to the game.

So, what I decided was that you can pass the language as an argument to the game on the game settings like you're doing. 
That's a simple fix to the user since we cannot deal with all games since they have different flags.
