### ISSUE TITLE
 Blank screen accessing specific game page (Chicory: A Colorful Tale)

### ISSUE THREAD

**Issue by AdrienLombard** [Heroic-Games-Launcher/HeroicGamesLauncher#831]
**Describe the bug**
Blank screen when specifically clicking on "Chicory: A Colorful Tale" in my library.
Was meant to be corrected with issue #785, but still doesn't work with a slightly different error message

**Add Logs**

[22108:1229/153758.535629:INFO:CONSOLE(2)] "TypeError: Cannot read properties of undefined (reading 'length')", source: file:///opt/Heroic/resources/app.asar/build/static/js/4.acb218c9.chunk.js (2)
[22108:1229/153758.535678:INFO:CONSOLE(1)] "[object Object]", source: file:///opt/Heroic/resources/app.asar/build/static/js/5.7d7c4eef.chunk.js (1)

**To Reproduce**

1. Start Heroic
2. Go to Library with no filter
3. Click on "Chicory: A Colorful Tale" entry (not the install button)
4. Screen goes blank

**Expected behavior**
Game page should appear

**Screenshots**
[https://i.ibb.co/nfZXfvD/Capture-d-cran-de-2021-12-16-10-57-35.png](https://i.ibb.co/nfZXfvD/Capture-d-cran-de-2021-12-16-10-57-35.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Heroic Version: 2.0.0 Roronoa Zoro
- Game: Chicory: A Colorful Tale
- Wine/Proton version: Wine 7.0-rc1
- Hardware specs (RAM, CPU, GPU): 32GB, AMD Ryzen 7 5700G

**Additional context**
The problem does not seem to exist on any other game of my library.
If I click the "install" button of Chicory directly from the library, it seems to install correctly
I tried to delete ~/.config/heroic and ~/.config/legendary as suggested in the troubleshooting section of the wiki, without success.

**Comment by flavioislima** [comment]
Can you open the dev tools using the debug item on the tray icon? And check if the error is more specific?

**Comment by flavioislima** [comment]
Actually, I think for that you will need to run Heroic in dev mode following the steps on the Readme.
So install nodejs v16 ( using NVM is ideal, don't install v17 since it has some major changes and it's breaking some things in heroic right now). 
then clone the repository with git or download the zip file, run `npm install` inside the heroic folder, then run `npm start` , actually its better to open two terminals on the folder and run: `npm run react-start` on one and `npm run electron` on the other, so you will have both logs.

**Comment by AdrienLombard** [comment]
When opening the dev tools, the first error seems to be a little bit more specific :
[https://i.ibb.co/frpFg21/Capture-d-cran-du-2021-12-30-11-35-37.png](https://i.ibb.co/frpFg21/Capture-d-cran-du-2021-12-30-11-35-37.png)

I'll install nodejs to try to get more info about the second error.

**Comment by AdrienLombard** [comment]
And here are some more informations I gathered:
[https://i.ibb.co/j8YvtPS/Capture-d-cran-de-2021-12-30-12-27-31.png](https://i.ibb.co/j8YvtPS/Capture-d-cran-de-2021-12-30-12-27-31.png)

**Comment by flavioislima** [comment]
> And here are some more informations I gathered: https://i.ibb.co/j8YvtPS/Capture-d-cran-de-2021-12-30-12-27-31.png
> 
> Feel free to ask if I can get you more informations

Perfect, now I know. I though the issue was on the game page but it was on the the System Requirements component. so I fixed it on Main. 
You can confirm that it works now by downloading the AppImage here:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/1637434759

Once the build finishes

**Comment by AdrienLombard** [comment]
It works now ! I was able to open the game page and install it without any problem.

Thanks for the great job ! :D

**Comment by flavioislima** [comment]
> It works now ! I was able to open the game page and install it without any problem.
> 
> Thanks for the great job ! :D

Nice and thanks for helping with the debug as well :D
