### ISSUE TITLE
Ignore articles ("The", "A", "An") when sorting the library

### ISSUE THREAD

**Issue by Noxellar** [Heroic-Games-Launcher/HeroicGamesLauncher#841]
**Is your feature request related to a problem? Please describe.**
Standard alphabetical sorting usually dictates that you ignore articles when sorting titles, i.e. "The Alto Collection" should be at the very top of the page, not down next to "Tharsis"

**Describe the solution you'd like**
Just ignore articles when sorting the library

**Describe alternatives you've considered**
N/A

**Additional context**
Shouldn't be like this where titles with "The" in them appear next to other "T" titles:
![image](https://user-images.githubusercontent.com/32978806/147797409-b9bf9c4c-dac8-464a-94bd-a8a533fb9369.png)

**Comment by flavioislima** [comment]
Hmm, I totally agree with the 'The' article, but about the 'an' and the 'a' I'm not 100% sure since games.
Its weird to me to put A plague Tale Innocence close to the other games that start with the letter P.
So I'll remove the THE for now but will keep the others and we can discuss this later, sounds good?
