### ISSUE TITLE
Show Developer/Publisher/Release Date on Game Info page

### ISSUE THREAD

**Issue by github12101** [Heroic-Games-Launcher/HeroicGamesLauncher#873]
Currently, on game info page, in this example, Heroic Games Launcher shows the following:
"Focus Home" (not even a full name of the Publisher)

Screenshot below:
![image](https://user-images.githubusercontent.com/1646393/148274272-85ef5ab3-d7b1-472d-9846-62267bfd79cd.png)

Instead, it should show the following:
Developer: Asobo Studio
Publisher: Focus Home Interactive
Release Date: 05/14/19

Just like Epic store page online:

![image](https://user-images.githubusercontent.com/1646393/148274377-37828608-259f-4708-b2a5-3b47a057919e.png)

That would be much better.

**Comment by arielj** [comment]
I'm closing this since it was implemented* here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3330

(*) some things to note:
- The information we get in the metadata is just `Focus Home` and not `Focus Home Interactive`, so we can't fix that
- We don't get the Publisher information in the metadata

So we show: the developer info (as we get it from in the metadata) and the release date only:
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/68ed97fd-b1c3-403a-b214-23ad0cb449e3)

Fetching the rest of information from another source will just add complexity with querying some endpoint, caching, etc, it's not really worth it.
