### ISSUE TITLE
White Border around selected toggle

### ISSUE THREAD

**Issue by LithRakoon** [Heroic-Games-Launcher/HeroicGamesLauncher#876]
### Try to get help on our Wiki first: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Troubleshooting

**Describe the bug**
When using a toggle it selects the toggle and creates an ugly white border around it

**Add Logs**
https://www.toptal.com/developers/hastebin/quwivecige.yaml

**To Reproduce**

1. Go to settings
2. Click on a toggle like the one from "exit to system tray"
3. See a white border around it appear

**Expected behavior**
no white border gets created, only the button itself changes color.

**Screenshots**
Toggle selected:
![image](https://user-images.githubusercontent.com/41258148/148307803-424981ec-a5f7-4820-903d-3375aff07787.png)
![image](https://user-images.githubusercontent.com/41258148/148307818-6d8c1e4b-08f2-4fcd-9c5d-30af8333e3e0.png)

Toggle not selected:
![image](https://user-images.githubusercontent.com/41258148/148307874-d510d902-c871-4b60-8d41-35a6d40f2d7b.png)
![image](https://user-images.githubusercontent.com/41258148/148307898-e6805c64-2432-4a36-8a3f-dd2d51c6961d.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Heroic Version: 2.0.1
- Game: N/A
- Wine/Proton version: N/A
- Hardware specs (RAM, CPU, GPU): 16gb, Ryzen 3 2200g, RTX 1050TI

**Comment by flavioislima** [comment]
this is because of the accessibility improvements we did recently.
so since Heroic can be navigated by keyboard and we are working on making it compatible with a joystick as well, this is the 'effect' it gets when selected.
@arielj perhaps we can style this to be more subtle. I'm not sure if its possible though. Would need some investigation.

**Comment by arielj** [comment]
I'll do some reseach, usually `:focus-visible` can be used to only show an outline when focusing with the keyboard, but because of the trick to make a slider with the label+hiddeninput+span it's not working 100% as expected (it hides the outline for mouse clicks but the keyboard focus disappears after toggling).
