### ISSUE TITLE
custom DXVK

### ISSUE THREAD

**Issue by logan001** [Heroic-Games-Launcher/HeroicGamesLauncher#907]
how can i add/change DXVK to one or more versions of DXVK?

**Comment by flavioislima** [comment]
Please, for questions use discord or discussion sobre this is not an issue.

**Comment by logan001** [comment]
well i don't use discord and i know is not an issue. if you had the time to answer like this you could had actually told me the solution not just close the issue and direct me to another page to ask the same question.

**Comment by flavioislima** [comment]
I'm just saying thar Issues is called like that because it's an ISSUE. And we also have a message saying that you should NOT erase the template when opening issues. 
So you break the rules and still want good will. 
Here is your answer just because I am a really nice guy:

You can just disable the install dxvk on prefix and install your dxvk version using winetricks or the script that comes with it.
Heroic installs only the latest since its pretty rare a game doesn't work with newest version.

**Comment by logan001** [comment]
ok. thats more like an answer.
i was actually wanted to add it as a request cause sometimes its useful to be able to change it. but i thought that this might already be possible somehow and i don't know how to do it.
anyway thank you.
