### ISSUE TITLE
Links in sidebar are not working on Linux

### ISSUE THREAD

**Issue by CommandMC** [Heroic-Games-Launcher/HeroicGamesLauncher#968]
**Describe the bug**
When clicking the Kofi, Patreon, or Discord links in the sidebar, nothing actually opens

**Add Logs**
When a button is clicked, `Check failed: chdir(current_directory) == 0` is printed out

**To Reproduce**

1. Open Heroic
2. Click any of the 3 links in the sidebar (Kofi, Patreon, Discord)

**Expected behavior**
Well, the link should open

**Desktop (please complete the following information):**

- OS: Arch Linux, KDE Plasma. **Not reproducible on Windows**
- Heroic Version [e.g. 22]: 2.1.1 (currently this is also the main version)
- Game: N/A
- Wine/Proton version: N/A
- Hardware specs (RAM, CPU, GPU): N/A

**Comment by imLinguin** [comment]
This is probably due to change in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/electron/utils.ts#L262 . Probably we should check if path starts with http or https and run `xdg-open` or [shell.openExternal](https://www.electronjs.org/docs/latest/api/shell/#shellopenexternalurl-options)
